/*
 * File: app/store/ticketfbcount.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.ticketfbcount', {
    extend: 'Ext.data.Store',
    alias: 'store.ticketfbcount',

    requires: [
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json',
        'Ext.data.Field'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'MyJsonStore2',
            data: [
                {
                    text: 0,
                    value: '50亩'
                },
                {
                    text: 1,
                    value: '100亩'
                },
                {
                    text: 2,
                    value: '200亩'
                },
                {
                    text: 3,
                    value: '300亩'
                },
                {
                    text: 4,
                    value: '400亩'
                },
                {
                    text: 5,
                    value: '500亩'
                },
                {
                    text: 6,
                    value: '600亩'
                },
                {
                    text: 7,
                    value: '700亩'
                },
                {
                    text: 8,
                    value: '900亩'
                },
                {
                    text: 10,
                    value: '1000亩'
                }
            ],
            proxy: {
                type: 'ajax',
                reader: {
                    type: 'json'
                }
            },
            fields: [
                {
                    name: 'text'
                },
                {
                    name: 'value'
                }
            ]
        }, cfg)]);
    }
});