/*
 * File: app/store/zbgmstore.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.zbgmstore', {
    extend: 'Ext.data.Store',
    alias: 'store.zbgmstore',

    requires: [
        'MyApp.model.zbsglb',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            autoLoad: true,
            filterOnLoad: false,
            model: 'MyApp.model.zbsglb',
            storeId: 'zbgmstore',
            pageSize: 15,
            proxy: {
                type: 'ajax',
                url: 'getgmlb',
                reader: {
                    type: 'json',
                    root: 'root'
                }
            }
        }, cfg)]);
    }
});