package cn.edu.bnu.land.model;

// Generated 2013-12-13 9:53:57 by Hibernate Tools 4.0.0

/**
 * InfoChannel generated by hbm2java
 */
public class InfoChannel implements java.io.Serializable {

	private Integer channelId;
	private String channelName;

	public InfoChannel() {
	}

	public InfoChannel(String channelName) {
		this.channelName = channelName;
	}

	public Integer getChannelId() {
		return this.channelId;
	}

	public void setChannelId(Integer channelId) {
		this.channelId = channelId;
	}

	public String getChannelName() {
		return this.channelName;
	}

	public void setChannelName(String channelName) {
		this.channelName = channelName;
	}

}
