package cn.edu.bnu.land.model;

// Generated 2013-10-5 11:38:45 by Hibernate Tools 4.0.0

/**
 * RssChannelItems generated by hbm2java
 */
public class RssChannelItems implements java.io.Serializable {

	private Integer itemsId;
	private RssChannel rssChannel;
	private String items;
	private String areaCode;
	private RssItemsDetails rssItemsDetails;

	public RssChannelItems() {
	}

	public RssChannelItems(RssChannel rssChannel) {
		this.rssChannel = rssChannel;
	}

	public RssChannelItems(RssChannel rssChannel, String items,
			String areaCode, RssItemsDetails rssItemsDetails) {
		this.rssChannel = rssChannel;
		this.items = items;
		this.areaCode = areaCode;
		this.rssItemsDetails = rssItemsDetails;
	}

	public Integer getItemsId() {
		return this.itemsId;
	}

	public void setItemsId(Integer itemsId) {
		this.itemsId = itemsId;
	}

	public RssChannel getRssChannel() {
		return this.rssChannel;
	}

	public void setRssChannel(RssChannel rssChannel) {
		this.rssChannel = rssChannel;
	}

	public String getItems() {
		return this.items;
	}

	public void setItems(String items) {
		this.items = items;
	}

	public String getAreaCode() {
		return this.areaCode;
	}

	public void setAreaCode(String areaCode) {
		this.areaCode = areaCode;
	}

	public RssItemsDetails getRssItemsDetails() {
		return this.rssItemsDetails;
	}

	public void setRssItemsDetails(RssItemsDetails rssItemsDetails) {
		this.rssItemsDetails = rssItemsDetails;
	}

}
