package cn.edu.bnu.land.model;

// Generated 2014-5-18 23:58:44 by Hibernate Tools 4.0.0

import java.util.Date;

import org.springframework.stereotype.Repository;

/**
 * Zbckdl generated by hbm2java
 */
@Repository
public class Zbckdl implements java.io.Serializable {

	private Integer id;
	private Integer jcid;
	private String zbpcbh;
	private Float bcfbed;
	private Date fbrq;
	private String bz;
	private String qt;

	public Zbckdl() {
	}

	public Zbckdl(Integer jcid, String zbpcbh, Float bcfbed, Date fbrq,
			String bz, String qt) {
		this.jcid = jcid;
		this.zbpcbh = zbpcbh;
		this.bcfbed = bcfbed;
		this.fbrq = fbrq;
		this.bz = bz;
		this.qt = qt;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getJcid() {
		return this.jcid;
	}

	public void setJcid(Integer jcid) {
		this.jcid = jcid;
	}

	public String getZbpcbh() {
		return this.zbpcbh;
	}

	public void setZbpcbh(String zbpcbh) {
		this.zbpcbh = zbpcbh;
	}

	public Float getBcfbed() {
		return this.bcfbed;
	}

	public void setBcfbed(Float bcfbed) {
		this.bcfbed = bcfbed;
	}

	public Date getFbrq() {
		return this.fbrq;
	}

	public void setFbrq(Date fbrq) {
		this.fbrq = fbrq;
	}

	public String getBz() {
		return this.bz;
	}

	public void setBz(String bz) {
		this.bz = bz;
	}

	public String getQt() {
		return this.qt;
	}

	public void setQt(String qt) {
		this.qt = qt;
	}

}
