package cn.edu.bnu.land.model;

// Generated 2014-5-18 23:58:44 by Hibernate Tools 4.0.0

import java.util.Date;

import org.springframework.stereotype.Repository;

/**
 * Zbgglb generated by hbm2java
 */
@Repository
public class Zbgglb implements java.io.Serializable {

	private Integer id;
	private String zbpcbh;
	private Float dwed;
	private Integer sl;
	private String jylx;
	private Float dj;
	private Date fbrq;
	private Date sqjzrq;
	private Date bzjjzrq;
	private Date jjksrq;
	private Date jjjsrq;
	private Integer dqhj;
	private String pczt;
	private String pcbz;
	private String pcqt;
	private Boolean sfzj;

	public Zbgglb() {
	}

	public Zbgglb(String zbpcbh, Float dwed, Integer sl, String jylx, Float dj,
			Date fbrq, Date sqjzrq, Date bzjjzrq, Date jjksrq, Date jjjsrq,
			Integer dqhj, String pczt, String pcbz, String pcqt, Boolean sfzj) {
		this.zbpcbh = zbpcbh;
		this.dwed = dwed;
		this.sl = sl;
		this.jylx = jylx;
		this.dj = dj;
		this.fbrq = fbrq;
		this.sqjzrq = sqjzrq;
		this.bzjjzrq = bzjjzrq;
		this.jjksrq = jjksrq;
		this.jjjsrq = jjjsrq;
		this.dqhj = dqhj;
		this.pczt = pczt;
		this.pcbz = pcbz;
		this.pcqt = pcqt;
		this.sfzj = sfzj;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getZbpcbh() {
		return this.zbpcbh;
	}

	public void setZbpcbh(String zbpcbh) {
		this.zbpcbh = zbpcbh;
	}

	public Float getDwed() {
		return this.dwed;
	}

	public void setDwed(Float dwed) {
		this.dwed = dwed;
	}

	public Integer getSl() {
		return this.sl;
	}

	public void setSl(Integer sl) {
		this.sl = sl;
	}

	public String getJylx() {
		return this.jylx;
	}

	public void setJylx(String jylx) {
		this.jylx = jylx;
	}

	public Float getDj() {
		return this.dj;
	}

	public void setDj(Float dj) {
		this.dj = dj;
	}

	public Date getFbrq() {
		return this.fbrq;
	}

	public void setFbrq(Date fbrq) {
		this.fbrq = fbrq;
	}

	public Date getSqjzrq() {
		return this.sqjzrq;
	}

	public void setSqjzrq(Date sqjzrq) {
		this.sqjzrq = sqjzrq;
	}

	public Date getBzjjzrq() {
		return this.bzjjzrq;
	}

	public void setBzjjzrq(Date bzjjzrq) {
		this.bzjjzrq = bzjjzrq;
	}

	public Date getJjksrq() {
		return this.jjksrq;
	}

	public void setJjksrq(Date jjksrq) {
		this.jjksrq = jjksrq;
	}

	public Date getJjjsrq() {
		return this.jjjsrq;
	}

	public void setJjjsrq(Date jjjsrq) {
		this.jjjsrq = jjjsrq;
	}

	public Integer getDqhj() {
		return this.dqhj;
	}

	public void setDqhj(Integer dqhj) {
		this.dqhj = dqhj;
	}

	public String getPczt() {
		return this.pczt;
	}

	public void setPczt(String pczt) {
		this.pczt = pczt;
	}

	public String getPcbz() {
		return this.pcbz;
	}

	public void setPcbz(String pcbz) {
		this.pcbz = pcbz;
	}

	public String getPcqt() {
		return this.pcqt;
	}

	public void setPcqt(String pcqt) {
		this.pcqt = pcqt;
	}

	public Boolean getSfzj() {
		return this.sfzj;
	}

	public void setSfzj(Boolean sfzj) {
		this.sfzj = sfzj;
	}

}
