package cn.edu.bnu.land.model;

// Generated 2014-5-25 20:00:20 by Hibernate Tools 4.0.0

import java.util.Date;

import org.springframework.stereotype.Repository;

/**
 * Zbjpcjjl generated by hbm2java
 */
@Repository
public class Zbjpcjjl implements java.io.Serializable {

	private Integer id;
	private String zbpcbh;
	private String userid;
	private Date cjsj;
	private Float cj;
	private Integer sgsl;
	private String pcbz;
	private String pczt;

	public Zbjpcjjl() {
	}

	public Zbjpcjjl(String zbpcbh, String userid, Date cjsj, Float cj,
			Integer sgsl, String pcbz, String pczt) {
		this.zbpcbh = zbpcbh;
		this.userid = userid;
		this.cjsj = cjsj;
		this.cj = cj;
		this.sgsl = sgsl;
		this.pcbz = pcbz;
		this.pczt = pczt;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getZbpcbh() {
		return this.zbpcbh;
	}

	public void setZbpcbh(String zbpcbh) {
		this.zbpcbh = zbpcbh;
	}

	public String getUserid() {
		return this.userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

	public Date getCjsj() {
		return this.cjsj;
	}

	public void setCjsj(Date cjsj) {
		this.cjsj = cjsj;
	}

	public Float getCj() {
		return this.cj;
	}

	public void setCj(Float cj) {
		this.cj = cj;
	}

	public Integer getSgsl() {
		return this.sgsl;
	}

	public void setSgsl(Integer sgsl) {
		this.sgsl = sgsl;
	}

	public String getPcbz() {
		return this.pcbz;
	}

	public void setPcbz(String pcbz) {
		this.pcbz = pcbz;
	}

	public String getPczt() {
		return this.pczt;
	}

	public void setPczt(String pczt) {
		this.pczt = pczt;
	}

}
