/*
 * File: app/model/jp.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.model.jp', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.Field'
    ],

    fields: [
        {
            name: 'zbpcbh',
            type: 'string'
        },
        {
            name: 'dwed',
            type: 'float'
        },
        {
            name: 'sl',
            type: 'int'
        },
        {
            name: 'sgzsl',
            type: 'int'
        },
        {
            name: 'dj',
            type: 'float'
        },
        {
            name: 'zgcj',
            type: 'float'
        },
        {
            name: 'jjksrq',
            type: 'date'
        },
        {
            name: 'kssj',
            type: 'string'
        },
        {
            name: 'pczt',
            type: 'string'
        },
        {
            name: 'zdjj',
            type: 'float'
        },
        {
            name: 'pcqt',
            type: 'string'
        }
    ]
});