/*
 * File: app/view/Extract.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.Extract', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.Extract',

    height: 462,
    width: 762,
    autoScroll: true,
    layout: {
        type: 'border'
    },
    title: '字段存储设置',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    region: 'center',
                    layout: {
                        align: 'stretch',
                        type: 'vbox'
                    },
                    bodyPadding: 10,
                    header: false,
                    title: '',
                    items: [
                        {
                            xtype: 'container',
                            height: 450,
                            width: 752,
                            layout: {
                                align: 'middle',
                                pack: 'center',
                                type: 'hbox'
                            },
                            items: [
                                {
                                    xtype: 'gridpanel',
                                    flex: 1,
                                    height: 400,
                                    id: 'webGrid',
                                    margin: 5,
                                    title: '网站数据字段列表',
                                    forceFit: true,
                                    store: 'lyjfieldStore',
                                    columns: [
                                        {
                                            xtype: 'gridcolumn',
                                            width: 329,
                                            dataIndex: 'webdataField',
                                            text: ''
                                        }
                                    ],
                                    selModel: Ext.create('Ext.selection.CheckboxModel', {

                                    }),
                                    dockedItems: [
                                        {
                                            xtype: 'toolbar',
                                            dock: 'top',
                                            items: [
                                                {
                                                    xtype: 'button',
                                                    handler: function(button, event) {
                                                        var win=new Ext.Window({
                                                            height: 170,
                                                            width: 400,
                                                            id:'jsdadafieldWindow',
                                                            layout: {
                                                                type: 'absolute'
                                                            },
                                                            title: '添加',
                                                            modal:'true',
                                                            items: [
                                                            {
                                                                xtype: 'form',
                                                                height: 220,
                                                                jsonSubmit: true,
                                                                id:'jsdadafield_add_Form',
                                                                layout: {
                                                                    type: 'absolute'
                                                                },
                                                                bodyPadding: 10,
                                                                url: 'add_jsdadafield',
                                                                title: '',
                                                                items: [

                                                                {
                                                                    xtype: 'textfield',
                                                                    id:'webdataField',
                                                                    name:'webdataField',
                                                                    x: 15,
                                                                    y: 20,
                                                                    width: 300,
                                                                    fieldLabel: '字段名称',
                                                                    labelAlign: 'right'
                                                                },


                                                                {
                                                                    xtype: 'button',
                                                                    x: 115,
                                                                    y: 100,
                                                                    width: 50,
                                                                    text: '确定',
                                                                    handler:function()
                                                                    {

                                                                        var myform=Ext.getCmp('jsdadafield_add_Form').getForm();    
                                                                        if (myform.isValid()) { // make sure the form contains valid data before submitting
                                                                            myform.submit({
                                                                                success: function(form, action) {
                                                                                    Ext.Msg.alert('提示', action.result.msg);

                                                                                    var mystore=Ext.StoreMgr.get('lyjfieldStore'); //获得store对象
                                                                                    //在load事件中添加参数
                                                                                    mystore.load(
                                                                                    {params:{
                                                                                        start:"0",
                                                                                        limit:"10"

                                                                                    }} );
                                                                                    win.close();
                                                                                },
                                                                                failure: function(form, action) {
                                                                                    Ext.Msg.alert('提示', '保存失败！');
                                                                                    win.close();
                                                                                }
                                                                            });
                                                                        } else { 
                                                                            Ext.Msg.alert('注意', '填写信息不能为空，请检查！');
                                                                        }


                                                                        return;

                                                                    }
                                                                },
                                                                {
                                                                    xtype: 'button',
                                                                    handler: function(button, event) {
                                                                        win.close();
                                                                    },
                                                                    x: 230,
                                                                    y: 100,
                                                                    width: 50,
                                                                    text: '取消'
                                                                }
                                                                ]
                                                            }
                                                            ]
                                                        });



                                                        win.show();
                                                    },
                                                    text: '添加'
                                                },
                                                {
                                                    xtype: 'button',
                                                    handler: function(button, event) {

                                                        var grid=this.up('grid');
                                                        var record =grid.getSelectionModel().getSelection();

                                                        if(record.length===0){
                                                            Ext.Msg.alert('提示','请先选择您要操作的行！');    
                                                            return;
                                                        }
                                                        else
                                                        {
                                                            var ids='';
                                                            for(var i=0;i<record.length;i++)
                                                            {
                                                                ids+=record[i].get("id");
                                                                if(i<record.length-1)ids=ids+",";
                                                            }

                                                            Ext.Ajax.request({
                                                                waitMsg:'正在发送，请等待...',
                                                                url:'del_jsdadafield',
                                                                params:{ids:ids},                          
                                                                success:function(response){
                                                                    Ext.Msg.alert('success','删除成功！');                
                                                                    var mystore=Ext.StoreMgr.get('lyjfieldStore'); //获得store对象
                                                                    //在load事件中添加参数
                                                                    mystore.load(
                                                                    {params:{
                                                                        start:"0",
                                                                        limit:"10"
                                                                    }} );
                                                                },
                                                                failure:function(){
                                                                    Ext.Msg.alert('failed','删除失败！');

                                                                }
                                                            });
                                                        }

                                                    },
                                                    text: '删除'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'pagingtoolbar',
                                            dock: 'bottom',
                                            width: 100,
                                            displayInfo: true,
                                            displayMsg: '{0} - {1} 条，共计{2}条',
                                            emptyMsg: '没有数据',
                                            store: 'lyjfieldStore'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'gridpanel',
                                    flex: 1,
                                    height: 400,
                                    id: 'localGrid',
                                    margin: 5,
                                    title: '本地数据字段列表',
                                    forceFit: true,
                                    store: 'lyjfieldStore2',
                                    columns: [
                                        {
                                            xtype: 'gridcolumn',
                                            width: 320,
                                            dataIndex: 'localdataField',
                                            text: ''
                                        }
                                    ],
                                    dockedItems: [
                                        {
                                            xtype: 'toolbar',
                                            dock: 'top',
                                            items: [
                                                {
                                                    xtype: 'button',
                                                    handler: function(button, event) {
                                                        var win=new Ext.Window({
                                                            height: 170,
                                                            width: 400,
                                                            id:'jsdadafield2Window',
                                                            layout: {
                                                                type: 'absolute'
                                                            },
                                                            title: '添加',
                                                            modal:'true',
                                                            items: [
                                                            {
                                                                xtype: 'form',
                                                                height: 220,
                                                                jsonSubmit: true,
                                                                id:'jsdadafield2_add_Form',
                                                                layout: {
                                                                    type: 'absolute'
                                                                },
                                                                bodyPadding: 10,
                                                                url: 'add_jsdadafield2',
                                                                title: '',
                                                                items: [

                                                                {
                                                                    xtype: 'textfield',
                                                                    id:'localdataField',
                                                                    name:'localdataField',
                                                                    x: 15,
                                                                    y: 20,
                                                                    width: 300,
                                                                    fieldLabel: '字段名称',
                                                                    labelAlign: 'right'
                                                                },


                                                                {
                                                                    xtype: 'button',
                                                                    x: 115,
                                                                    y: 100,
                                                                    width: 50,
                                                                    text: '确定',
                                                                    handler:function()
                                                                    {

                                                                        var myform=Ext.getCmp('jsdadafield2_add_Form').getForm();    
                                                                        if (myform.isValid()) { // make sure the form contains valid data before submitting
                                                                            myform.submit({
                                                                                success: function(form, action) {
                                                                                    Ext.Msg.alert('提示', action.result.msg);

                                                                                    var mystore=Ext.StoreMgr.get('lyjfieldStore2'); //获得store对象
                                                                                    //在load事件中添加参数
                                                                                    mystore.load(
                                                                                    {params:{
                                                                                        start:"0",
                                                                                        limit:"10"

                                                                                    }} );
                                                                                    win.close();
                                                                                },
                                                                                failure: function(form, action) {
                                                                                    Ext.Msg.alert('提示', '保存失败！');
                                                                                    win.close();
                                                                                }
                                                                            });
                                                                        } else { 
                                                                            Ext.Msg.alert('注意', '填写信息不能为空，请检查！');
                                                                        }


                                                                        return;

                                                                    }
                                                                },
                                                                {
                                                                    xtype: 'button',
                                                                    handler: function(button, event) {
                                                                        win.close();
                                                                    },
                                                                    x: 230,
                                                                    y: 100,
                                                                    width: 50,
                                                                    text: '取消'
                                                                }
                                                                ]
                                                            }
                                                            ]
                                                        });



                                                        win.show();
                                                    },
                                                    text: '添加'
                                                },
                                                {
                                                    xtype: 'button',
                                                    handler: function(button, event) {
                                                        var grid=this.up('grid');
                                                        var record =grid.getSelectionModel().getSelection();

                                                        if(record.length===0){
                                                            Ext.Msg.alert('提示','请先选择您要操作的行！');    
                                                            return;
                                                        }
                                                        else
                                                        {
                                                            var ids='';
                                                            for(var i=0;i<record.length;i++)
                                                            {
                                                                ids+=record[i].get("id");
                                                                if(i<record.length-1)ids=ids+",";
                                                            }

                                                            Ext.Ajax.request({
                                                                waitMsg:'正在发送，请等待...',
                                                                url:'del_jsdadafield2',
                                                                params:{ids:ids},                          
                                                                success:function(response){
                                                                    Ext.Msg.alert('success','删除成功！');                
                                                                    var mystore=Ext.StoreMgr.get('lyjfield2Store'); //获得store对象
                                                                    //在load事件中添加参数
                                                                    mystore.load(
                                                                    {params:{
                                                                        start:"0",
                                                                        limit:"10"
                                                                    }} );
                                                                },
                                                                failure:function(){
                                                                    Ext.Msg.alert('failed','删除失败！');

                                                                }
                                                            });
                                                        }

                                                    },
                                                    text: '删除'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'pagingtoolbar',
                                            dock: 'bottom',
                                            width: 360,
                                            displayInfo: true,
                                            displayMsg: '{0} - {1} 条，共计{2}条',
                                            emptyMsg: '没有数据',
                                            store: 'lyjfieldStore2'
                                        }
                                    ],
                                    selModel: Ext.create('Ext.selection.CheckboxModel', {

                                    })
                                },
                                {
                                    xtype: 'container',
                                    height: 30,
                                    width: 49,
                                    layout: {
                                        align: 'middle',
                                        pack: 'center',
                                        type: 'hbox'
                                    },
                                    items: [
                                        {
                                            xtype: 'button',
                                            handler: function(button, event) {
                                                var grid1 = Ext.getCmp('webGrid'); 
                                                var grid2 = Ext.getCmp('localGrid'); 
                                                var record1 = grid1.getSelectionModel().getSelection();


                                                var record2 = grid2.getSelectionModel().getSelection();


                                                if(record1.length===0 || record2.length===0){
                                                    Ext.Msg.alert('提示','请选择您要操作的数据字段！');    
                                                    return;
                                                }
                                                else
                                                {
                                                    var ids1='';
                                                    for(var i=0;i<record1.length;i++)
                                                    {
                                                        ids1+=record1[i].data.webdataField;
                                                        if(i<record1.length-1)ids1=ids1+",";
                                                    }
                                                    var ids2='';
                                                    for(var j=0;j<record2.length;j++)
                                                    {
                                                        ids2+=record2[j].data.localdataField;
                                                        if(j<record2.length-1)ids2=ids2+",";
                                                    }
                                                    Ext.Ajax.request({
                                                        waitMsg:'正在发送，请等待...',
                                                        url:'add_fieldmapping',
                                                        params:{ids1:ids1,ids2:ids2},                          
                                                        success:function(response){
                                                            Ext.Msg.alert('success','添加成功！');                
                                                            var mystore=Ext.StoreMgr.get('lyjfieldmappingStore'); //获得store对象
                                                            //在load事件中添加参数
                                                            mystore.load(
                                                            {params:{
                                                                start:"0",
                                                                limit:"10"
                                                            }} );
                                                        },
                                                        failure:function(){
                                                            Ext.Msg.alert('failed','添加失败！');

                                                        }
                                                    });
                                                }

                                            },
                                            width: 42,
                                            text: '='
                                        }
                                    ]
                                },
                                {
                                    xtype: 'gridpanel',
                                    flex: 1,
                                    height: 400,
                                    margin: 5,
                                    width: 711,
                                    title: '字段对应结果',
                                    forceFit: true,
                                    store: 'lyjfieldmappingStore',
                                    columns: [
                                        {
                                            xtype: 'gridcolumn',
                                            width: 710,
                                            dataIndex: 'fieldmapping',
                                            text: ''
                                        }
                                    ],
                                    selModel: Ext.create('Ext.selection.CheckboxModel', {

                                    }),
                                    dockedItems: [
                                        {
                                            xtype: 'toolbar',
                                            dock: 'top',
                                            items: [
                                                {
                                                    xtype: 'button',
                                                    handler: function(button, event) {
                                                        var grid=this.up('grid');
                                                        var record =grid.getSelectionModel().getSelection();

                                                        if(record.length===0){
                                                            Ext.Msg.alert('提示','请先选择您要操作的行！');    
                                                            return;
                                                        }
                                                        else
                                                        {
                                                            var ids='';
                                                            for(var i=0;i<record.length;i++)
                                                            {
                                                                ids+=record[i].get("id");
                                                                if(i<record.length-1)ids=ids+",";
                                                            }

                                                            Ext.Ajax.request({
                                                                waitMsg:'正在发送，请等待...',
                                                                url:'del_fieldmapping',
                                                                params:{ids:ids},                          
                                                                success:function(response){
                                                                    Ext.Msg.alert('success','删除成功！');                
                                                                    var mystore=Ext.StoreMgr.get('lyjfieldmappingStore'); //获得store对象
                                                                    //在load事件中添加参数
                                                                    mystore.load(
                                                                    {params:{
                                                                        start:"0",
                                                                        limit:"10"
                                                                    }} );
                                                                },
                                                                failure:function(){
                                                                    Ext.Msg.alert('failed','删除失败！');

                                                                }
                                                            });
                                                        }

                                                    },
                                                    text: '删除'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'pagingtoolbar',
                                            dock: 'bottom',
                                            width: 360,
                                            displayInfo: true,
                                            displayMsg: '{0} - {1} 条，共计{2}条',
                                            emptyMsg: '没有数据',
                                            store: 'lyjfieldmappingStore'
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});