/*
 * File: app/view/infoVotePublishTab.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.infoVotePublishTab', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.infoVotePublishTab',

    requires: [
        'Ext.form.Panel',
        'Ext.form.field.Text',
        'Ext.grid.Panel',
        'Ext.grid.RowNumberer',
        'Ext.grid.View',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.selection.CheckboxModel'
    ],

    layout: 'fit',
    title: '网上投票-发起投票',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    layout: 'auto',
                    bodyPadding: 10,
                    title: 'My Form',
                    items: [
                        {
                            xtype: 'textfield',
                            fieldLabel: '投票主题',
                            name: 'voteTitle'
                        },
                        {
                            xtype: 'textfield',
                            fieldLabel: '投票简介',
                            name: 'voteIntro'
                        },
                        {
                            xtype: 'textfield',
                            fieldLabel: '开始时间',
                            name: 'voteStarttime',
                            inputType: 'datetime'
                        },
                        {
                            xtype: 'textfield',
                            fieldLabel: '结束时间',
                            name: 'voteEndtime',
                            inputType: 'datetime'
                        },
                        {
                            xtype: 'textfield',
                            width: 256,
                            fieldLabel: '发起人',
                            name: 'voteVoter'
                        },
                        {
                            xtype: 'gridpanel',
                            title: '投票选项',
                            store: 'InfoVoteoptionStore',
                            columns: [
                                {
                                    xtype: 'rownumberer'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'voptionId',
                                    text: '选项ID'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'voptionContent',
                                    text: '选项内容'
                                }
                            ],
                            dockedItems: [
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    items: [
                                        {
                                            xtype: 'button',
                                            text: '增加选项'
                                        },
                                        {
                                            xtype: 'button',
                                            text: '删除选项'
                                        }
                                    ]
                                }
                            ],
                            selModel: Ext.create('Ext.selection.CheckboxModel', {

                            })
                        },
                        {
                            xtype: 'button',
                            text: '确定发起投票'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});