/*
 * File: app/view/infoLetterDetailTab.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.infoLetterDetailTab', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.infoLetterDetailTab',

    requires: [
        'Ext.form.Panel',
        'Ext.form.field.TextArea',
        'Ext.form.RadioGroup',
        'Ext.form.field.Radio',
        'Ext.button.Button'
    ],

    title: '群众来信-详细',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    height: 395,
                    layout: 'absolute',
                    bodyPadding: 10,
                    title: 'My Form',
                    items: [
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: '来信主题',
                            readOnly: true
                        },
                        {
                            xtype: 'textfield',
                            x: 10,
                            y: 40,
                            width: 230,
                            fieldLabel: '姓名',
                            readOnly: true
                        },
                        {
                            xtype: 'textfield',
                            x: 540,
                            y: 70,
                            width: 230,
                            fieldLabel: '电话',
                            readOnly: true
                        },
                        {
                            xtype: 'textfield',
                            x: 540,
                            y: 40,
                            width: 230,
                            fieldLabel: '地址',
                            readOnly: true
                        },
                        {
                            xtype: 'textfield',
                            x: 270,
                            y: 70,
                            width: 230,
                            fieldLabel: '身份证号',
                            readOnly: true
                        },
                        {
                            xtype: 'textfield',
                            x: 270,
                            y: 40,
                            width: 230,
                            fieldLabel: '电子邮件',
                            readOnly: true
                        },
                        {
                            xtype: 'textfield',
                            x: 10,
                            y: 70,
                            width: 230,
                            fieldLabel: '来信时间',
                            readOnly: true
                        },
                        {
                            xtype: 'textareafield',
                            anchor: '100%',
                            x: 10,
                            y: 100,
                            fieldLabel: '来信内容',
                            readOnly: true
                        },
                        {
                            xtype: 'textareafield',
                            anchor: '100%',
                            x: 10,
                            y: 170,
                            fieldLabel: '回复内容'
                        },
                        {
                            xtype: 'radiogroup',
                            x: 10,
                            y: 240,
                            fieldLabel: '是否公示：',
                            items: [
                                {
                                    xtype: 'radiofield',
                                    boxLabel: '是'
                                },
                                {
                                    xtype: 'radiofield',
                                    boxLabel: '否'
                                }
                            ]
                        },
                        {
                            xtype: 'button',
                            x: 10,
                            y: 280,
                            text: '确定并发送邮件'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});