/*
 * File: app/view/infoArticleNDZCTab.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.infoArticleNDZCTab', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.infoArticleNDZCTab',

    requires: [
        'Ext.tab.Panel',
        'Ext.tab.Tab',
        'Ext.grid.Panel',
        'Ext.grid.RowNumberer',
        'Ext.grid.column.Date',
        'Ext.grid.View',
        'Ext.selection.CheckboxModel',
        'Ext.form.field.Date',
        'Ext.toolbar.Paging'
    ],

    id: 'infoArticleNDZCTab',
    layout: 'fit',
    title: '信息管理与发布>>农地转出',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'tabpanel',
                    height: 421,
                    id: '',
                    bodyPadding: 10,
                    items: [
                        {
                            xtype: 'panel',
                            layout: 'fit',
                            title: '已发布',
                            items: [
                                {
                                    xtype: 'gridpanel',
                                    id: 'articlePubGrid3',
                                    collapsible: false,
                                    title: '',
                                    forceFit: true,
                                    store: 'ArticlePubNDZCStore',
                                    columns: [
                                        {
                                            xtype: 'rownumberer',
                                            width: 47,
                                            text: '记录号'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'articleName',
                                            text: '信息标题',
                                            tooltip: '点击查看详细信息'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'articleAuthor',
                                            text: '作者'
                                        },
                                        {
                                            xtype: 'datecolumn',
                                            dataIndex: 'articlePublishtime',
                                            text: '发布时间'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'isMailpush',
                                            text: '是否已邮件推送'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'isSmspush',
                                            text: '是否已短信推送'
                                        }
                                    ],
                                    selModel: Ext.create('Ext.selection.CheckboxModel', {

                                    }),
                                    dockedItems: [
                                        {
                                            xtype: 'toolbar',
                                            dock: 'top',
                                            frame: false,
                                            enableOverflow: true,
                                            items: [
                                                {
                                                    xtype: 'datefield',
                                                    id: 'searchDatePub3',
                                                    width: 204,
                                                    fieldLabel: '起始时间',
                                                    labelWidth: 70,
                                                    format: 'Y-m-d'
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    id: 'searchKeywordPub3',
                                                    width: 211,
                                                    fieldLabel: '',
                                                    labelWidth: 50,
                                                    emptyText: '请输入搜索关键字'
                                                },
                                                {
                                                    xtype: 'button',
                                                    handler: function(button, event) {
                                                        var getDate = Ext.util.Format.date(Ext.getCmp('searchDatePub3').getValue(),'Y-m-d');
                                                        var getKeyword = Ext.getCmp('searchKeywordPub3').getValue();
                                                        var mystore=Ext.StoreMgr.get('ArticlePubNDZCStore'); //获得store对象
                                                        //在load事件中添加参数
                                                        mystore.load(
                                                        {params:{
                                                            start:"0",
                                                            limit:"25",
                                                            searchKeyword:getKeyword,
                                                            searchDate:getDate
                                                        }
                                                    }
                                                    );
                                                    },
                                                    icon: 'images/file_view0.png',
                                                    text: '搜索'
                                                },
                                                {
                                                    xtype: 'button',
                                                    handler: function(button, event) {

                                                        Ext.widget("infoAritcleNDZCNewWindow").show();
                                                    },
                                                    icon: 'images/table_add.png',
                                                    text: '发布新信息'
                                                },
                                                {
                                                    xtype: 'button',
                                                    handler: function(button, event) {
                                                        var m_store_ticket=Ext.StoreMgr.get('ArticlePubNDZCStore'); //获得store对象
                                                        //构建选择用户窗口
                                                        win = Ext.create('Ext.window.Window',
                                                        {title: '农地转出信息推送',
                                                            minWidth: 700,
                                                            minHeight: 380,
                                                            layout: 'fit',
                                                            items: [
                                                            {
                                                                xtype: 'gridpanel',
                                                                autoRender: false,
                                                                height: 240,
                                                                id: 'NDZC_pushgrid',
                                                                width: 700,
                                                                title: '',
                                                                forceFit: true,
                                                                store: 'gxuserStoreNDZC',
                                                                columns: [
                                                                {
                                                                    xtype: 'rownumberer',
                                                                    width: 48,
                                                                    text: '记录号'
                                                                },
                                                                {
                                                                    xtype: 'gridcolumn',
                                                                    width: 82,
                                                                    dataIndex: 'username',
                                                                    text: '用户名'
                                                                },
                                                                {
                                                                    xtype: 'gridcolumn',
                                                                    width: 161,
                                                                    dataIndex: 'name',
                                                                    text: '注册人姓名'
                                                                },
                                                                {
                                                                    xtype: 'gridcolumn',
                                                                    width: 168,
                                                                    dataIndex: 'email',
                                                                    text: '邮箱'
                                                                },
                                                                {
                                                                    xtype: 'gridcolumn',
                                                                    width: 126,
                                                                    dataIndex: 'phone',
                                                                    text: '电话'
                                                                },
                                                                {
                                                                    xtype: 'gridcolumn',
                                                                    dataIndex: 'cardId',
                                                                    text: '身份证号'
                                                                },
                                                                {
                                                                    xtype: 'gridcolumn',
                                                                    dataIndex: 'lawman_name',
                                                                    text: '法人'
                                                                },
                                                                {
                                                                    xtype: 'gridcolumn',
                                                                    dataIndex: 'company_name',
                                                                    text: '公司名称'
                                                                },
                                                                {
                                                                    xtype: 'gridcolumn',
                                                                    hidden: true,
                                                                    dataIndex: 'id',
                                                                    text: 'id'
                                                                }
                                                                ],
                                                                dockedItems: [
                                                                {
                                                                    xtype: 'pagingtoolbar',
                                                                    dock: 'bottom',
                                                                    width: 360,
                                                                    displayInfo: true,
                                                                    displayMsg: '显示{0} - {1} 条，共计{2}条',
                                                                    emptyMsg: '没有数据',
                                                                    store: 'gxuserStoreNDZC'
                                                                },
                                                                {
                                                                    xtype: 'toolbar',
                                                                    dock: 'top',
                                                                    items: [
                                                                    {
                                                                        xtype: 'textfield',
                                                                        id: 'searchUsers_ndzc',
                                                                        width: 157,
                                                                        fieldLabel: ''
                                                                    },
                                                                    {
                                                                        xtype: 'button',
                                                                        handler: function(button, event) {
                                                                            var mystore=Ext.StoreMgr.get('gxuserStoreNDZC'); //获得store对象
                                                                            var myvalue=Ext.getCmp('searchUsers_ndzc').getValue();
                                                                            //在load事件中添加参数
                                                                            mystore.load(
                                                                            {params:{
                                                                                start:"0",
                                                                                limit:"10",
                                                                                searchUsers:myvalue

                                                                            }
                                                                        }
                                                                        );


                                                                    },
                                                                    border: '',
                                                                    text: '搜索'
                                                                },
                                                                {
                                                                    xtype: 'label',
                                                                    id: 'userChoice_lblndzc',
                                                                    width: 150,
                                                                    text: 'iiiiii'
                                                                },
                                                                {
                                                                    xtype: 'label',
                                                                    id: 'choiceUserLbl3',
                                                                    width: 150,
                                                                    text: ''
                                                                }
                                                                ]
                                                            }
                                                            ],
                                                            selModel: Ext.create('Ext.selection.CheckboxModel', {
                                                            }),
                                                            listeners: {
                                                                cellclick: {
                                                                    fn: me.onNDZC_pushgridCellClick,
                                                                    scope: me
                                                                }
                                                            }
                                                        },
                                                        {
                                                            xtype: 'container',
                                                            height: 126,
                                                            layout: {
                                                                type: 'absolute'
                                                            },
                                                            items: [
                                                            {
                                                                xtype: 'checkboxfield',
                                                                id:'sendMail_cboxndzc',
                                                                x: 240,
                                                                y: 20,
                                                                fieldLabel: '',
                                                                boxLabel: '发送邮件',
                                                                checked: true
                                                            },
                                                            {
                                                                xtype: 'checkboxfield',
                                                                id:'sendSMS_cboxndzc',
                                                                x: 340,
                                                                y: 20,
                                                                fieldLabel: '',
                                                                boxLabel: '发送短信',
                                                                checked: false
                                                            },
                                                            {
                                                                xtype: 'checkboxfield',
                                                                id:'pushall_cboxndzc',
                                                                x: -1,
                                                                y: 10,
                                                                fieldLabel: '',
                                                                boxLabel: '发送给全部用户',
                                                                checked: false
                                                            },
                                                            {
                                                                xtype: 'button',
                                                                handler: function(button, event) {
                                                                    //var my_grid=this.up('grid');
                                                                    var my_grid=Ext.getCmp('NDZC_pushgrid');
                                                                    var my_record =my_grid.getSelectionModel().getSelection();

                                                                    //获取用户选中的记录id
                                                                    //var my_lbl=Ext.getCmp("userChoice_lblndzc");
                                                                    //var my_ids=my_lbl.text;

                                                                    //用来获得“推送给全部用户”checkbox是否勾选,以及邮件和短信checkbox是否勾选
                                                                    var mycheckall=Ext.getCmp('pushall_cboxndzc').getValue();
                                                                    var mycheckMail=Ext.getCmp('sendMail_cboxndzc').getValue();
                                                                    var mycheckSMS=Ext.getCmp('sendSMS_cboxndzc').getValue();


                                                                    //都没有选择，提示用户
                                                                    if(my_record.length===0 && mycheckall===false){
                                                                        Ext.Msg.alert('提示','请先选择您要操作的行！');
                                                                        return;
                                                                    }
                                                                    //推送给全部用户
                                                                    else if (my_record.length===0 && mycheckall===true){

                                                                        //发送邮件
                                                                        if(mycheckMail===true){
                                                                            Ext.Ajax.request({
                                                                                url:'setMailPushTrue',
                                                                                params:{
                                                                                    ids:ids,  //待推送地票Id
                                                                                    userAdresses: '', //推送目标用户id
                                                                                    chanelid:'3'
                                                                                },
                                                                                success:function(response){

                                                                                    var myobj=eval('('+response.responseText+')');
                                                                                    if(myobj.success==="true")
                                                                                    {
                                                                                        Ext.Msg.alert('提示','邮件发送成功！');
                                                                                        win.close();
                                                                                        m_store_ticket.reload();
                                                                                    }
                                                                                    else
                                                                                    {
                                                                                        Ext.Msg.alert('提示','邮件发送失败！');
                                                                                    }

                                                                                },
                                                                                failure:function(){
                                                                                    Ext.Msg.alert('failed','邮件发送失败！');
                                                                                }
                                                                            });
                                                                        }

                                                                        //发送短信
                                                                        if(mycheckSMS===true){
                                                                            Ext.Ajax.request({
                                                                                url:'setSMSPushTrue',
                                                                                params:{
                                                                                    ids:ids,  //待推送地票Id
                                                                                    userPhones: '', //推送目标用户id
                                                                                    chanelid:'3'
                                                                                },
                                                                                success:function(response){
                                                                                    var myobj=eval('('+response.responseText+')');
                                                                                    if(myobj.success==="true")
                                                                                    {
                                                                                        Ext.Msg.alert('提示','短信发送成功！');
                                                                                        win.close();
                                                                                        m_store_ticket.reload();
                                                                                    }
                                                                                    else
                                                                                    {
                                                                                        Ext.Msg.alert('提示','短信发送失败！');
                                                                                    }
                                                                                },
                                                                                failure:function(){
                                                                                    Ext.Msg.alert('failed','短信发送失败！');
                                                                                }
                                                                            });
                                                                        }
                                                                    }
                                                                    //推送给选定用户
                                                                    else
                                                                    {
                                                                        var userAdresses=''; var userPhones='';
                                                                        for(var i=0;i<my_record.length;i++)
                                                                        {
                                                                            userAdresses+=my_record[i].get("email");
                                                                            userPhones+=my_record[i].get("phone");
                                                                            if(i<my_record.length-1)
                                                                            {userAdresses=userAdresses+",";
                                                                                userPhones=userPhones+",";
                                                                            }
                                                                        }

                                                                        if(mycheckMail===true){
                                                                            //发送邮件
                                                                            Ext.Ajax.request({
                                                                                url:'setMailPushTrue',
                                                                                params:{
                                                                                    ids:ids,  //待推送地票Id
                                                                                    userAdresses:userAdresses,  //推送目标用户id
                                                                                    chanelid:'3'
                                                                                },
                                                                                success:function(response){
                                                                                    var myobj=eval('('+response.responseText+')');
                                                                                    if(myobj.success==="true")
                                                                                    {
                                                                                        Ext.Msg.alert('提示','邮件发送成功！');
                                                                                        win.close();
                                                                                        m_store_ticket.reload();
                                                                                    }
                                                                                    else
                                                                                    {
                                                                                        Ext.Msg.alert('提示','邮件发送失败！');
                                                                                    }


                                                                                },
                                                                                failure:function(){
                                                                                    Ext.Msg.alert('提示','邮件发送失败！');
                                                                                }
                                                                            });
                                                                        }

                                                                        //发送短信
                                                                        if(mycheckSMS===true){
                                                                            Ext.Ajax.request({
                                                                                url:'setSMSPushTrue',
                                                                                params:{
                                                                                    ids:ids,  //待推送地票Id
                                                                                    userPhones: userPhones,
                                                                                    chanelid:'3'
                                                                                },
                                                                                success:function(response){
                                                                                    var myobj=eval('('+response.responseText+')');
                                                                                    if(myobj.success==="true")
                                                                                    {
                                                                                        Ext.Msg.alert('提示','短信发送成功！');
                                                                                        win.close();
                                                                                        m_store_ticket.reload();
                                                                                    }
                                                                                    else
                                                                                    {
                                                                                        Ext.Msg.alert('提示','短信发送失败！');
                                                                                    }
                                                                                },
                                                                                failure:function(){
                                                                                    Ext.Msg.alert('failed','短信发送失败！');
                                                                                }
                                                                            });
                                                                        }
                                                                    }

                                                                },
                                                                x: 270,
                                                                y: 60,
                                                                width: 110,
                                                                href: '',
                                                                text: '发送'
                                                            }
                                                            ]
                                                        }
                                                        ]


                                                    }
                                                    );

                                                    //判断用户是否已经选择待推送的信息
                                                    var mygrid=this.up('grid');
                                                    var myrecord =mygrid.getSelectionModel().getSelection();
                                                    if(myrecord.length===0){
                                                        Ext.Msg.alert('提示','请先选择您要操作的行！');
                                                        return;
                                                    }
                                                    else //弹出选择用户窗口
                                                    {
                                                        var ids='';
                                                        for(var i=0;i<myrecord.length;i++)
                                                        {
                                                            ids+=myrecord[i].get("articleId");
                                                            if(i<myrecord.length-1)ids=ids+",";
                                                        }
                                                        var myidslbl=Ext.getCmp('userChoice_lblndzc');
                                                        myidslbl.text=ids;

                                                        myidslbl.hidden=true;

                                                        win.show();

                                                        //弹出的窗口自动加载用户数据
                                                        var mstore=Ext.StoreMgr.get('gxuserStoreNDZC'); //获得store对象
                                                        //在load事件中添加参数
                                                        mstore.load(
                                                        {params:{
                                                            start:'0',
                                                            limit:'10',
                                                            searchUsers:''

                                                        }
                                                    }
                                                    );
                                                }

                                                    },
                                                    icon: '',
                                                    text: '信息推送'
                                                },
                                                {
                                                    xtype: 'button',
                                                    handler: function(button, event) {
                                                        var grid = Ext.getCmp('articlePubGrid3');
                                                        //var gird = this.down('grid');
                                                        var record = grid.getSelectionModel().getSelection();

                                                        if(record.length === 0){
                                                            Ext.Msg.alert('提示','请先选择您要操作的行！');
                                                            return;

                                                        }else{


                                                            //var articleIds='';
                                                            //for(var i=0;i<record.length;i++)
                                                            //{
                                                            //    articleIds+=record[i].get("articleId");
                                                            //    if(i<record.length-1)articleIds=articleIds+",";
                                                            //}
                                                            //Ext.Msg.alert('提示',articleIds);



                                                            var  articleIds =new Array(record.length);
                                                            for(var i = 0;i<record.length;i++){
                                                                articleIds[i] = record[i].get("articleId");

                                                            }
                                                            //Ext.Msg.alert('提示',articleIds);



                                                            Ext.Ajax.request({
                                                                url:'update_articleToRecycle',
                                                                params:{articleIds:articleIds},

                                                                success:function(response){
                                                                    Ext.Msg.alert('success','文章放入到回收站');
                                                                    var mystore = Ext.StoreMgr.get('ArticleRecNDZCStore');
                                                                    mystore.load();
                                                                    var mystore2 = Ext.StoreMgr.get('ArticlePubNDZCStore');
                                                                    mystore2.load();

                                                                }

                                                            });

                                                        }
                                                    },
                                                    icon: 'images/table_delete.png',
                                                    text: '移入回收站'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'pagingtoolbar',
                                            dock: 'bottom',
                                            height: 36,
                                            width: 360,
                                            displayInfo: true,
                                            store: 'ArticlePubNDZCStore'
                                        }
                                    ],
                                    listeners: {
                                        cellclick: {
                                            fn: me.onArticlegridCellClick,
                                            scope: me
                                        }
                                    }
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            layout: 'fit',
                            title: '草稿箱',
                            items: [
                                {
                                    xtype: 'gridpanel',
                                    id: 'articleDraftGrid3',
                                    collapsible: false,
                                    title: '',
                                    forceFit: true,
                                    store: 'ArticleDraftNDZCStore',
                                    columns: [
                                        {
                                            xtype: 'rownumberer',
                                            width: 47,
                                            text: '记录号'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'articleName',
                                            text: '信息标题'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'articleAuthor',
                                            text: '作者'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            width: 420,
                                            dataIndex: 'articleContent',
                                            text: '文章内容'
                                        }
                                    ],
                                    selModel: Ext.create('Ext.selection.CheckboxModel', {

                                    }),
                                    dockedItems: [
                                        {
                                            xtype: 'toolbar',
                                            dock: 'top',
                                            frame: false,
                                            enableOverflow: true,
                                            items: [
                                                {
                                                    xtype: 'datefield',
                                                    hidden: true,
                                                    id: 'searchDateDraft3',
                                                    width: 204,
                                                    fieldLabel: '起始时间',
                                                    labelWidth: 70,
                                                    format: 'Y-m-d'
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    id: 'searchKeywordDraft3',
                                                    width: 211,
                                                    fieldLabel: '',
                                                    labelWidth: 50,
                                                    emptyText: '请输入搜索关键字'
                                                },
                                                {
                                                    xtype: 'button',
                                                    handler: function(button, event) {
                                                        var getDate = Ext.util.Format.date(Ext.getCmp('searchDateDraft3').getValue(),'Y-m-d');
                                                        var getKeyword = Ext.getCmp('searchKeywordDraft3').getValue();
                                                        var mystore=Ext.StoreMgr.get('ArticleDraftNDZCStore'); //获得store对象
                                                        //在load事件中添加参数
                                                        mystore.load(
                                                        {params:{
                                                            start:"0",
                                                            limit:"25",
                                                            searchKeyword:getKeyword,
                                                            searchDate:getDate
                                                        }
                                                    }
                                                    );
                                                    },
                                                    icon: 'images/file_view0.png',
                                                    text: '搜索'
                                                },
                                                {
                                                    xtype: 'button',
                                                    handler: function(button, event) {
                                                        var grid = Ext.getCmp('articleDraftGrid3');

                                                        var record = grid.getSelectionModel().getSelection();

                                                        if(record.length === 0){
                                                            Ext.Msg.alert('提示','请先选择您要操作的行！');
                                                            return;

                                                        }else{

                                                            var  articleIds =new Array(record.length);
                                                            for(var i = 0;i<record.length;i++){
                                                                articleIds[i] = record[i].get("articleId");

                                                            }
                                                            //Ext.Msg.alert('提示',articleIds);



                                                            Ext.Ajax.request({
                                                                url:'update_articleToPubFromDraft',
                                                                params:{articleIds:articleIds},

                                                                success:function(response){
                                                                    Ext.Msg.alert('success','信息恢复到已发布');
                                                                    var mystore = Ext.StoreMgr.get('ArticleDraftNDZCStore');
                                                                    mystore.load();
                                                                    var mystore2 = Ext.StoreMgr.get('ArticlePubNDZCStore');
                                                                    mystore2.load();

                                                                }

                                                            });

                                                        }
                                                    },
                                                    icon: 'images/table_add.png',
                                                    text: '文章发布'
                                                },
                                                {
                                                    xtype: 'button',
                                                    handler: function(button, event) {
                                                        var grid = Ext.getCmp('articleDraftGrid3');

                                                        var record = grid.getSelectionModel().getSelection();

                                                        if(record.length === 0){
                                                            Ext.Msg.alert('提示','请先选择您要操作的行！');
                                                            return;

                                                        }else{

                                                            var  articleIds =new Array(record.length);
                                                            for(var i = 0;i<record.length;i++){
                                                                articleIds[i] = record[i].get("articleId");

                                                            }
                                                            //Ext.Msg.alert('提示',articleIds);



                                                            Ext.Ajax.request({
                                                                url:'del_articleByIds',
                                                                params:{articleIds:articleIds},

                                                                success:function(response){
                                                                    Ext.Msg.alert('success','信息已删除');
                                                                    var mystore = Ext.StoreMgr.get('ArticleDraftNDZCStore');
                                                                    mystore.load();


                                                                }

                                                            });

                                                        }
                                                    },
                                                    icon: 'images/table_delete.png',
                                                    text: '彻底删除'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'pagingtoolbar',
                                            dock: 'bottom',
                                            height: 36,
                                            width: 360,
                                            displayInfo: true,
                                            store: 'ArticleDraftNDZCStore'
                                        }
                                    ],
                                    listeners: {
                                        cellclick: {
                                            fn: me.onArticlegrid2CellClick,
                                            scope: me
                                        }
                                    }
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            layout: 'fit',
                            title: '回收站',
                            items: [
                                {
                                    xtype: 'gridpanel',
                                    id: 'articleRecGrid3',
                                    collapsible: false,
                                    title: '',
                                    forceFit: true,
                                    store: 'ArticleRecNDZCStore',
                                    columns: [
                                        {
                                            xtype: 'rownumberer',
                                            width: 47,
                                            text: '记录号'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'articleName',
                                            text: '信息标题'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'articleAuthor',
                                            text: '作者'
                                        },
                                        {
                                            xtype: 'datecolumn',
                                            dataIndex: 'articlePublishtime',
                                            text: '发布时间'
                                        }
                                    ],
                                    selModel: Ext.create('Ext.selection.CheckboxModel', {

                                    }),
                                    dockedItems: [
                                        {
                                            xtype: 'toolbar',
                                            dock: 'top',
                                            frame: false,
                                            enableOverflow: true,
                                            items: [
                                                {
                                                    xtype: 'datefield',
                                                    id: 'searchDateRec3',
                                                    width: 204,
                                                    fieldLabel: '起始时间',
                                                    labelWidth: 70,
                                                    format: 'Y-m-d'
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    id: 'searchKeywordRec3',
                                                    width: 211,
                                                    fieldLabel: '',
                                                    labelWidth: 50,
                                                    emptyText: '请输入搜索关键字'
                                                },
                                                {
                                                    xtype: 'button',
                                                    handler: function(button, event) {
                                                        var getDate = Ext.util.Format.date(Ext.getCmp('searchDateRec3').getValue(),'Y-m-d');
                                                        var getKeyword = Ext.getCmp('searchKeywordRec3').getValue();
                                                        var mystore=Ext.StoreMgr.get('ArticleRecNDZCStore'); //获得store对象
                                                        //在load事件中添加参数
                                                        mystore.load(
                                                        {params:{
                                                            start:"0",
                                                            limit:"25",
                                                            searchKeyword:getKeyword,
                                                            searchDate:getDate
                                                        }
                                                    }
                                                    );
                                                    },
                                                    icon: 'images/file_view0.png',
                                                    text: '搜索'
                                                },
                                                {
                                                    xtype: 'button',
                                                    handler: function(button, event) {
                                                        var grid = Ext.getCmp('articleRecGrid3');

                                                        var record = grid.getSelectionModel().getSelection();

                                                        if(record.length === 0){
                                                            Ext.Msg.alert('提示','请先选择您要操作的行！');
                                                            return;

                                                        }else{

                                                            var  articleIds =new Array(record.length);
                                                            for(var i = 0;i<record.length;i++){
                                                                articleIds[i] = record[i].get("articleId");

                                                            }
                                                            //Ext.Msg.alert('提示',articleIds);



                                                            Ext.Ajax.request({
                                                                url:'update_articleToPubFromRec',
                                                                params:{articleIds:articleIds},

                                                                success:function(response){
                                                                    Ext.Msg.alert('success','文章恢复到已发布');
                                                                    var mystore = Ext.StoreMgr.get('ArticleRecNDZCStore');
                                                                    mystore.load();
                                                                    var mystore2 = Ext.StoreMgr.get('ArticlePubNDZCStore');
                                                                    mystore2.load();

                                                                }

                                                            });

                                                        }
                                                    },
                                                    icon: 'images/table_add.png',
                                                    text: '信息恢复'
                                                },
                                                {
                                                    xtype: 'button',
                                                    handler: function(button, event) {
                                                        var grid = Ext.getCmp('articleRecGrid3');

                                                        var record = grid.getSelectionModel().getSelection();

                                                        if(record.length === 0){
                                                            Ext.Msg.alert('提示','请先选择您要操作的行！');
                                                            return;

                                                        }else{

                                                            var  articleIds =new Array(record.length);
                                                            for(var i = 0;i<record.length;i++){
                                                                articleIds[i] = record[i].get("articleId");

                                                            }
                                                            //Ext.Msg.alert('提示',articleIds);



                                                            Ext.Ajax.request({
                                                                url:'del_articleByIds',
                                                                params:{articleIds:articleIds},

                                                                success:function(response){
                                                                    Ext.Msg.alert('success','文章已删除');
                                                                    var mystore = Ext.StoreMgr.get('ArticleRecNDZCStore');
                                                                    mystore.load();


                                                                }

                                                            });

                                                        }
                                                    },
                                                    icon: 'images/table_delete.png',
                                                    text: '彻底删除'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'pagingtoolbar',
                                            dock: 'bottom',
                                            height: 36,
                                            width: 360,
                                            displayInfo: true,
                                            store: 'ArticleRecNDZCStore'
                                        }
                                    ],
                                    listeners: {
                                        cellclick: {
                                            fn: me.onArticlegrid3CellClick,
                                            scope: me
                                        }
                                    }
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onArticlegridCellClick: function(tableview, td, cellIndex, record, tr, rowIndex, e, eOpts) {
        if(cellIndex === undefined || cellIndex < 2) return;



        var win = new Ext.Window({

            title:'查看详细信息',
            closable:true,
            layout:'fit',
            items:[
            {
                xtype: 'form',
                height: 516,
                id: 'articleScanForm11',
                layout: {
                    type: 'absolute'
                },
                anchorSize: 100,
                bodyPadding: 10,
                jsonSubmit: true,
                items: [
                {
                    xtype: 'displayfield',
                    x: 10,
                    y: 210,
                    weight: 1,
                    height: 360,
                    width: 900,
                    fieldLabel: '内容',
                    id: 'articleContent',
                    name: 'articleContent'
                },
                {
                    xtype: 'displayfield',
                    width: 620,
                    fieldLabel: '名称',
                    id: 'articleName',
                    name: 'articleName'
                },
                {
                    xtype: 'displayfield',
                    x: 10,
                    y: 90,
                    width: 290,
                    fieldLabel: '作者',
                    id: 'articleAuthor',
                    name: 'articleAuthor'
                },
                {
                    xtype: 'displayfield',
                    x: 10,
                    y: 170,
                    width: 280,
                    fieldLabel: '发布时间',
                    id: 'articlePublishtime',
                    name: 'articlePublishtime'
                },
                {
                    xtype: 'displayfield',
                    x: 10,
                    y: 130,
                    width: 290,
                    fieldLabel: '信息来源',
                    id: 'articleSource',
                    name: 'articleSource'
                },{
                    xtype: 'displayfield',
                    x: 10,
                    y: 50,
                    id: 'channelId',
                    width: 320,
                    fieldLabel: '频道栏目',
                    name: 'channelId'


                }

                ]
            }
            ]


        });
        Ext.getCmp('articleContent').setValue(record.data.articleContent);
        Ext.getCmp('channelId').setValue('农地转出');
        Ext.getCmp('articleName').setValue(record.data.articleName);
        Ext.getCmp('articleAuthor').setValue(record.data.articleAuthor);
        Ext.getCmp('articlePublishtime').setValue(record.data.articlePublishtime);
        Ext.getCmp('articleSource').setValue(record.data.articleSource);

        win.show();
    },

    onArticlegrid2CellClick: function(tableview, td, cellIndex, record, tr, rowIndex, e, eOpts) {
        if (cellIndex === undefined || cellIndex < 2) return;

        //var newArticleTab = Ext.widget('infoArtilceScanTab');
        var channelStore = Ext.StoreMgr.get('InfoChannelStore');
        var win = new Ext.Window({

            title: '编辑',
            closable: true,
            layout: 'fit',
            jsonSubmit: true,
            items: [{
                xtype: 'form',
                height: 588,
                id: 'articleDraftUpdateForm11',

                jsonSubmit: true,
                layout: {
                    type: 'absolute'
                },
                anchorSize: 100,
                bodyPadding: 10,

                items: [{
                    xtype: 'textfield',
                    id: 'articleId',
                    fieldLabel: '信息ID',
                    hidden: true,
                    name: 'articleId'
                },
                {
                    xtype: 'textfield',
                    id:'articleIsrecycle',
                    fieldLabel: '是否在回收站',
                    hidden: true,
                    name: 'articleIsrecycle'
                },
                {
                    xtype: 'textfield',
                    id: 'articleIsdraft',
                    fieldLabel: '是否在草稿箱',
                    hidden: true,
                    name: 'articleIsdraft'
                },
                {
                    xtype: 'htmleditor',
                    x: 10,
                    y: 130,
                    weight: 1,
                    height: 410,
                    id: 'articleContent',
                    width: 760,
                    fieldLabel: '内容',
                    name: 'articleContent'
                },
                {
                    xtype: 'textfield',
                    id: 'articleName',
                    width: 760,
                    fieldLabel: '名称',
                    name: 'articleName'
                },
                {
                    xtype: 'textfield',
                    x: 10,
                    y: 50,
                    id: 'articleAuthor',
                    width: 330,
                    fieldLabel: '作者',
                    name: 'articleAuthor'

                },
                {
                    xtype: 'combobox',
                    x: 450,
                    y: 50,
                    id: 'channelId',
                    width: 320,
                    fieldLabel: '频道栏目',
                    name: 'channelId',
                    displayField: 'channelName',
                    store: channelStore,
                    valueField: 'channelId',
                    value:3
                },
                {
                    xtype: 'textfield',
                    x: 450,
                    y: 90,
                    hidden: true,
                    id: 'articlePublishtime',
                    width: 320,
                    fieldLabel: '发布时间',
                    name: 'articlePublishtime',
                    inputType: 'date'
                },
                {
                    xtype: 'textfield',
                    x: 10,
                    y: 90,
                    id: 'articleSource',
                    width: 330,
                    fieldLabel: '信息来源',
                    name: 'articleSource'
                },{
                    xtype: 'button',
                    x: 118,
                    y: 561,
                    width: 90,
                    text: '保存',
                    handler: function() {
                        var myform = Ext.getCmp('articleDraftUpdateForm11').getForm();
                        if (myform.isValid()) { // make sure the form contains valid data before submitting
                            myform.submit({
                                url:'update_draftArticle',
                                success: function(form, action) {
                                    Ext.Msg.alert('success', '修改内容成功');

                                    var mystore = Ext.StoreMgr.get('ArticleDraftNDZCStore'); //获得store对象
                                    mystore.load();
                                    //{
                                    //params: {
                                    // start: "0",
                                    // limit: "25"
                                    //searchField: Ext.getCmp('searchField_pubNewDynamic').getValue(),
                                    //searchDate: Ext.util.Format.date(Ext.getCmp('searchDate_pubNewDynamic').getValue(), 'Y-m-d');
                                    //}
                                    //}
                                    // );

                                    win.close();

                                },
                                failure: function(form, action) {
                                    Ext.Msg.alert('failure', '修改内容失败');
                                    win.close();
                                }
                            });
                        } else {
                            Ext.Msg.alert('注意', '填写信息不能为空，请检查！');
                        }

                        return;

                    }
                },
                {
                    xtype: 'button',
                    x: 250,
                    y: 560,
                    width: 90,
                    text: '取消',
                    handler:function(){
                        win.close();
                    }
                }


                ]

            }]

        });
        Ext.getCmp('articleId').setValue(record.data.articleId);
        //Ext.getCmp('channelId').setValue('建言献策');
        Ext.getCmp('articleIsrecycle').setValue(record.data.articleIsrecycle);
        Ext.getCmp('articleIsdraft').setValue(record.data.articleIsdraft);
        Ext.getCmp('articleContent').setValue(record.data.articleContent);
        Ext.getCmp('articleName').setValue(record.data.articleName);
        Ext.getCmp('articleAuthor').setValue(record.data.articleAuthor);
        Ext.getCmp('articleSource').setValue(record.data.articleSource);
        Ext.getCmp('articlePublishtime').setValue(record.data.articlePublishtime);


        win.show();
    },

    onArticlegrid3CellClick: function(tableview, td, cellIndex, record, tr, rowIndex, e, eOpts) {
        if (cellIndex === undefined || cellIndex < 2) return;

        var channelStore = Ext.StoreMgr.get('InfoChannelStore');
        var win = new Ext.Window({

            title: '文章编辑',
            closable: true,
            layout: 'fit',
            jsonSubmit: true,
            items: [{
                xtype: 'form',
                height: 588,
                id: 'articleRecUpdateForm11',

                jsonSubmit: true,
                layout: {
                    type: 'absolute'
                },
                anchorSize: 100,
                bodyPadding: 10,

                items: [{
                    xtype: 'textfield',
                    id: 'articleId',
                    width: 760,
                    fieldLabel: '文章ID',
                    hidden: true,
                    name: 'articleId'
                },
                {
                    xtype: 'combobox',
                    x: 350,
                    y: 50,
                    id: 'channelId',
                    width: 290,
                    fieldLabel: '频道栏目',
                    name: 'channelId',
                    displayField: 'channelName',
                    store: channelStore,
                    valueField: 'channelId',
                    value:3
                },
                {
                    xtype: 'textfield',
                    id: 'articleIsrecycle',
                    width: 760,
                    fieldLabel: '是否在回收站',
                    hidden: true,
                    name: 'articleIsrecycle'
                },
                {
                    xtype: 'textfield',
                    id: 'articleIsdraft',
                    width: 760,
                    fieldLabel: '是否在草稿箱',
                    hidden: true,
                    name: 'articleIsdraft'
                },
                {
                    xtype: 'htmleditor',
                    x: 10,
                    y: 150,
                    weight: 1,
                    height: 360,
                    id: 'articleContent',
                    width: 760,
                    fieldLabel: '文章内容',
                    name: 'articleContent'
                },
                {
                    xtype: 'textfield',
                    id: 'articleName',
                    width: 620,
                    fieldLabel: '文章名称',
                    name: 'articleName'
                },
                {
                    xtype: 'textfield',
                    x: 10,
                    y: 50,
                    id: 'articleAuthor',
                    width: 290,
                    fieldLabel: '文章作者',
                    name: 'articleAuthor'
                },
                {
                    xtype: 'textfield',
                    x: 350,
                    y: 100,
                    id: 'articlePublishtime',
                    width: 290,
                    fieldLabel: '发布时间',
                    name: 'articlePublishtime',
                    inputType: 'date'
                },
                {
                    xtype: 'textfield',
                    x: 10,
                    y: 100,
                    id: 'articleSource',
                    width: 290,
                    fieldLabel: '文章来源',
                    name: 'articleSource'
                },
                {
                    xtype: 'button',
                    x: 118,
                    y: 561,
                    width: 90,
                    text: '保存',
                    handler: function() {
                        var myform = Ext.getCmp('articleRecUpdateForm11').getForm();
                        if (myform.isValid()) { // make sure the form contains valid data before submitting
                            myform.submit({
                                url:'update_recArticle',
                                success: function(form, action) {
                                    Ext.Msg.alert('success', '修改内容成功');

                                    var mystore = Ext.StoreMgr.get('ArticleRecNDZCStore'); //获得store对象
                                    mystore.load();
                                    //{
                                    //params: {
                                    // start: "0",
                                    // limit: "25"
                                    //searchField: Ext.getCmp('searchField_pubNewDynamic').getValue(),
                                    //searchDate: Ext.util.Format.date(Ext.getCmp('searchDate_pubNewDynamic').getValue(), 'Y-m-d');
                                    //}
                                    //}
                                    // );

                                    win.close();

                                },
                                failure: function(form, action) {
                                    Ext.Msg.alert('failure', '修改内容失败');
                                    win.close();
                                }
                            });
                        } else {
                            Ext.Msg.alert('注意', '填写信息不能为空，请检查！');
                        }

                        return;

                    }
                },
                {
                    xtype: 'button',
                    x: 250,
                    y: 560,
                    width: 90,
                    text: '取消',
                    handler:function(){
                        win.close();
                    }
                }]
            }]

        });
        Ext.getCmp('articleId').setValue(record.data.articleId);
        //Ext.getCmp('channelId').setValue(record.data.channelId);
        Ext.getCmp('articleIsrecycle').setValue(record.data.articleIsrecycle);
        Ext.getCmp('articleIsdraft').setValue(record.data.articleIsdraft);
        Ext.getCmp('articleContent').setValue(record.data.articleContent);
        Ext.getCmp('articleName').setValue(record.data.articleName);
        Ext.getCmp('articleAuthor').setValue(record.data.articleAuthor);
        Ext.getCmp('articleSource').setValue(record.data.articleSource);
        Ext.getCmp('articlePublishtime').setValue(record.data.articlePublishtime);


        win.show();
    }

});