/*
 * File: app/view/infoVoteResultTab.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.infoVoteResultTab', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.infoVoteResultTab',

    requires: [
        'Ext.form.Panel',
        'Ext.chart.Chart',
        'Ext.util.Point',
        'Ext.chart.axis.Category',
        'Ext.chart.axis.Numeric',
        'Ext.chart.series.Bar'
    ],

    layout: 'fit',
    title: '网上投票-结果',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    bodyPadding: 10,
                    title: 'My Form',
                    jsonSubmit: true,
                    url: 'get_voteResult',
                    items: [
                        {
                            xtype: 'chart',
                            height: 250,
                            width: 400,
                            animate: true,
                            insetPadding: 20,
                            store: 'InfoVoteoptionStore',
                            axes: [
                                {
                                    type: 'Category',
                                    fields: [
                                        'voptionContent'
                                    ],
                                    position: 'left',
                                    title: '投票选项'
                                },
                                {
                                    type: 'Numeric',
                                    fields: [
                                        'voptionNumber'
                                    ],
                                    position: 'bottom',
                                    title: '票数',
                                    maximum: 100,
                                    minimum: 0
                                }
                            ],
                            series: [
                                {
                                    type: 'bar',
                                    label: {
                                        display: 'insideEnd',
                                        field: 'voptionNumber',
                                        color: '#333',
                                        'text-anchor': 'middle'
                                    },
                                    axis: 'bottom',
                                    xField: 'voptionContent',
                                    yField: 'voptionNumber',
                                    xPadding: 10
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});