/*
 * File: app/view/lyj_addURL.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.lyj_addURL', {
    extend: 'Ext.window.Window',

    requires: [
        'Ext.form.Panel',
        'Ext.form.Label',
        'Ext.form.field.Text',
        'Ext.button.Button'
    ],

    height: 250,
    width: 400,
    layout: 'absolute',
    title: '编辑',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    height: 220,
                    layout: 'absolute',
                    bodyPadding: 10,
                    title: 'My Form',
                    items: [
                        {
                            xtype: 'label',
                            x: 37,
                            y: 20,
                            text: '原网站名称：'
                        },
                        {
                            xtype: 'label',
                            x: 40,
                            y: 50,
                            text: '原网站URL：'
                        },
                        {
                            xtype: 'label',
                            x: 13,
                            y: 80,
                            text: '修改后网站名称：'
                        },
                        {
                            xtype: 'label',
                            x: 40,
                            y: 110,
                            text: '修改后URL：'
                        },
                        {
                            xtype: 'textfield',
                            x: 110,
                            y: 20,
                            width: 250,
                            fieldLabel: ''
                        },
                        {
                            xtype: 'textfield',
                            x: 110,
                            y: 110,
                            width: 250,
                            fieldLabel: ''
                        },
                        {
                            xtype: 'textfield',
                            x: 110,
                            y: 80,
                            width: 250,
                            fieldLabel: ''
                        },
                        {
                            xtype: 'textfield',
                            x: 110,
                            y: 50,
                            width: 250,
                            fieldLabel: ''
                        },
                        {
                            xtype: 'button',
                            x: 110,
                            y: 150,
                            width: 50,
                            text: '确定'
                        },
                        {
                            xtype: 'button',
                            handler: function(button, event) {
                                win.close();
                            },
                            x: 230,
                            y: 150,
                            width: 50,
                            text: '取消'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});