/*
 * File: app/view/MainView.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MainView', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.MainView',

    requires: [
        'MyApp.view.infoArticleZXDTTab',
        'Ext.tab.Panel',
        'Ext.tab.Tab',
        'Ext.form.Label',
        'Ext.Img',
        'Ext.tree.Panel',
        'Ext.tree.View'
    ],

    id: 'myViewPort',
    layout: 'border',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'tabpanel',
                    region: 'center',
                    id: 'htglTabPanelMain',
                    activeTab: 0,
                    items: [
                        {
                            xtype: 'infoArticleZXDTTab'
                        }
                    ],
                    listeners: {
                        show: {
                            fn: me.onHtglTabPanelMainShow,
                            scope: me
                        }
                    }
                },
                {
                    xtype: 'panel',
                    region: 'north',
                    height: 150,
                    layout: 'fit',
                    items: [
                        {
                            xtype: 'label',
                            html: '<a href="j_spring_security_logout">退出      </a>'
                        },
                        {
                            xtype: 'label',
                            html: '<a href="http://localhost:8080/tdlz/" target="blank">       门户网站</a>',
                            text: ''
                        },
                        {
                            xtype: 'image',
                            height: 201,
                            width: 201,
                            src: 'images/title_htgl.png'
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    region: 'west',
                    split: true,
                    width: 150,
                    layout: 'accordion',
                    collapsible: true,
                    title: '管理面板',
                    items: [
                        {
                            xtype: 'treepanel',
                            height: 102,
                            title: '信息发布推送',
                            root: {
                                expanded: true,
                                children: [
                                    {
                                        id: 'infoArticleZXDTTab',
                                        text: '最新动态',
                                        icon: 'images/tubiao.png',
                                        leaf: true
                                    },
                                    {
                                        id: 'infoArticleTZGGTab',
                                        text: '通知公告',
                                        icon: 'images/tubiao.png',
                                        leaf: true
                                    },
                                    {
                                        id: 'infoArticleNDZCTab',
                                        text: '供地信息',
                                        icon: 'images/tubiao.png',
                                        leaf: true
                                    },
                                    {
                                        id: 'infoArticleNDZRTab',
                                        text: '需求信息',
                                        icon: 'images/tubiao.png',
                                        leaf: true
                                    },
                                    {
                                        id: 'infoArticleZJJYTab',
                                        text: '交记录易',
                                        icon: 'images/tubiao.png',
                                        leaf: true
                                    },
                                    {
                                        id: 'infoArticleJYLCTab',
                                        text: '交易流程',
                                        icon: 'images/tubiao.png',
                                        leaf: true
                                    },
                                    {
                                        id: 'infoArticleQRCodeTab',
                                        text: '二维码管理',
                                        icon: 'images/tubiao.png',
                                        leaf: true
                                    }
                                ]
                            },
                            rootVisible: false,
                            viewConfig: {

                            },
                            listeners: {
                                selectionchange: {
                                    fn: me.onTreepanelSelectionChange1,
                                    scope: me
                                }
                            }
                        },
                        {
                            xtype: 'treepanel',
                            title: '竞价交易管理',
                            root: {
                                expanded: true,
                                children: [
                                    {
                                        id: 'zbshrk',
                                        text: '指标审核入库',
                                        icon: '',
                                        leaf: true
                                    },
                                    {
                                        id: 'zblbfb',
                                        text: '指标发布',
                                        icon: '',
                                        leaf: true
                                    },
                                    {
                                        id: 'jylcgl',
                                        text: '交易流程管理',
                                        icon: '',
                                        leaf: true
                                    }
                                ]
                            },
                            rootVisible: false,
                            viewConfig: {

                            },
                            listeners: {
                                selectionchange: {
                                    fn: me.onTreepanelSelectionChange1111,
                                    scope: me
                                }
                            }
                        },
                        {
                            xtype: 'treepanel',
                            title: '交易态势分析',
                            root: {
                                expanded: true,
                                children: [
                                    {
                                        id: 'TaishiFind',
                                        text: '交易态势查询',
                                        icon: 'images/tubiao.png',
                                        leaf: true
                                    },
                                    {
                                        id: 'TaishiPrice',
                                        text: '按交易价格分析',
                                        icon: 'images/tubiao.png',
                                        leaf: true
                                    },
                                    {
                                        id: 'TaishiVolume',
                                        text: '按交易量分析',
                                        icon: 'images/tubiao.png',
                                        leaf: true
                                    },
                                    {
                                        id: 'TaishiNumber',
                                        text: '按交易次数分析',
                                        icon: 'images/tubiao.png',
                                        leaf: true
                                    },
                                    {
                                        id: 'TaishiArea',
                                        text: '按交易区域分析',
                                        icon: 'images/tubiao.png',
                                        leaf: true
                                    },
                                    {
                                        id: 'TaishiAlarm',
                                        text: '交易态势异常分析',
                                        icon: 'images/tubiao.png',
                                        leaf: true
                                    }
                                ]
                            },
                            rootVisible: false,
                            viewConfig: {

                            },
                            listeners: {
                                selectionchange: {
                                    fn: me.onTreepanelSelectionChange111111,
                                    scope: me
                                }
                            }
                        },
                        {
                            xtype: 'treepanel',
                            title: '收益分配溯源',
                            root: {
                                expanded: true,
                                children: [
                                    {
                                        id: 'ShouyiRegister',
                                        text: '收益登记',
                                        icon: 'images/tubiao.png',
                                        leaf: true
                                    },
                                    {
                                        id: 'ShouyiFind_Hetong',
                                        text: '收益查询',
                                        icon: 'images/tubiao.png',
                                        leaf: true
                                    },
                                    {
                                        id: 'ShouyiStat_Nonghu',
                                        text: '统计分析',
                                        icon: 'images/tubiao.png',
                                        leaf: true
                                    },
                                    {
                                        id: 'ShouyiAlarm',
                                        text: '异常分析',
                                        icon: 'images/tubiao.png',
                                        leaf: true
                                    }
                                ]
                            },
                            rootVisible: false,
                            viewConfig: {

                            },
                            listeners: {
                                selectionchange: {
                                    fn: me.onTreepanelSelectionChange1111111,
                                    scope: me
                                }
                            }
                        },
                        {
                            xtype: 'treepanel',
                            title: '信息检索与统计',
                            root: {
                                expanded: true,
                                children: [
                                    {
                                        id: '',
                                        text: '信息检索设置',
                                        icon: 'images/tubiao.png',
                                        children: [
                                            {
                                                id: 'Crawl',
                                                text: '检索网站设置',
                                                icon: 'images/tubiao.jpg',
                                                leaf: true
                                            },
                                            {
                                                id: 'CrawlInfo',
                                                text: '查看检索信息列表',
                                                icon: 'images/tubiao.jpg',
                                                leaf: true
                                            },
                                            {
                                                id: 'Extract',
                                                text: '字段存储设置',
                                                icon: 'images/tubiao.jpg',
                                                leaf: true
                                            },
                                            {
                                                id: 'Keywords',
                                                text: '查询主题词设置',
                                                icon: 'images/tubiao.jpg',
                                                leaf: true
                                            }
                                        ]
                                    },
                                    {
                                        id: 'ccQueryStatisticsTab',
                                        text: '查询与统计',
                                        icon: 'images/tubiao.png',
                                        leaf: true
                                    }
                                ]
                            },
                            rootVisible: false,
                            viewConfig: {

                            },
                            listeners: {
                                selectionchange: {
                                    fn: me.onTreepanelSelectionChange2,
                                    scope: me
                                }
                            }
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onHtglTabPanelMainShow: function(component, eOpts) {
        Ext.Ajax.request({
            url:'timer_creat_xml'

        });
    },

    onTreepanelSelectionChange1: function(model, selected, eOpts) {
        //var xtype = selected[0].get('id');
        //Ext.MessageBox.alert('xtype',xtype);
        //var tabPanel=Ext.ComponentQuery.query('tabpanel')[0];
        //tabPanel.removeAll(true);
        //tabPanel.add(Ext.widget(xtype));
        // Ext.MessageBox.alert('info444',title);

        var xtype = selected[0].get('id');
        var myTabPanel = Ext.getCmp('htglTabPanelMain');
        myTabPanel.removeAll(true);


        var xtypes=xtype.split(",");
        for(var i=0;i<xtypes.length;i++){
            myTabPanel.add(Ext.widget(xtypes[i]));
        }

        var mywin=Ext.create('Ext.window.Window',{
            title: '农地转入信息推送',
            minWidth: 700,
            minHeight: 380,
            layout: 'fit',
            items: [Ext.widget(xtypes[1])]
        });
        mywin.show();
    },

    onTreepanelSelectionChange1111: function(model, selected, eOpts) {
        var xtype = selected[0].get('id');
        var myTabPanel = Ext.getCmp('htglTabPanelMain');
        myTabPanel.removeAll(true);
        myTabPanel.add(Ext.widget(xtype));

    },

    onTreepanelSelectionChange111111: function(model, selected, eOpts) {
        var xtype = selected[0].get('id');
        var myTabPanel = Ext.getCmp('htglTabPanelMain');
        myTabPanel.removeAll(true);
        myTabPanel.add(Ext.widget(xtype));
    },

    onTreepanelSelectionChange1111111: function(model, selected, eOpts) {
        var xtype = selected[0].get('id');
        var myTabPanel = Ext.getCmp('htglTabPanelMain');
        myTabPanel.removeAll(true);
        myTabPanel.add(Ext.widget(xtype));
        if(xtype=='ShouyiStat_Nonghu'){
            myTabPanel.add(Ext.widget('ShouyiStat_Jianshe'));
        }
        if(xtype=='ShouyiFind_Hetong'){
            myTabPanel.add(Ext.widget('ShouyiFind_Zijin'));
        }

    },

    onTreepanelSelectionChange2: function(model, selected, eOpts) {
        var xtype = selected[0].get('id');
        //Ext.Msg.alert("",xtype);
        var myTabPanel = Ext.getCmp('htglTabPanelMain');
        //Ext.Msg.alert("",myTabPanel.id);
        myTabPanel.removeAll(true);
        myTabPanel.add(Ext.widget(xtype));
    }

});