/*
 * File: app/view/mmxg.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.mmxg', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.mmxg',

    requires: [
        'Ext.form.field.Text',
        'Ext.button.Button'
    ],

    height: 624,
    width: 807,
    layout: 'absolute',
    title: '密码修改',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'textfield',
                    x: 280,
                    y: 160,
                    fieldLabel: '原秘密'
                },
                {
                    xtype: 'textfield',
                    x: 280,
                    y: 210,
                    fieldLabel: '新密码'
                },
                {
                    xtype: 'textfield',
                    x: 280,
                    y: 260,
                    fieldLabel: '再次输入'
                },
                {
                    xtype: 'button',
                    x: 360,
                    y: 330,
                    width: 80,
                    text: '提交'
                }
            ]
        });

        me.callParent(arguments);
    }

});