/*
 * File: app/view/mycrzb.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.mycrzb', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.mycrzb',

    requires: [
        'Ext.grid.Panel',
        'Ext.grid.column.Number',
        'Ext.grid.View',
        'Ext.grid.plugin.CellEditing',
        'Ext.grid.feature.Grouping',
        'Ext.toolbar.Paging'
    ],

    height: 497,
    id: 'crzbdj',
    width: 1118,
    autoScroll: true,
    layout: 'fit',
    title: '<font size=\'2.5px\'>我的出让指标</font>',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'gridpanel',
                    cls: 'x-grid3-row TD',
                    height: 250,
                    width: 400,
                    title: '',
                    store: 'zbcrsh',
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            align: 'center',
                            dataIndex: 'crzbbh',
                            text: '指标编号'
                        },
                        {
                            xtype: 'gridcolumn',
                            align: 'center',
                            dataIndex: 'userid',
                            text: '用户名'
                        },
                        {
                            xtype: 'gridcolumn',
                            align: 'center',
                            dataIndex: 'fkxmbh',
                            text: '复垦项目编号'
                        },
                        {
                            xtype: 'gridcolumn',
                            align: 'center',
                            dataIndex: 'fkxmmc',
                            text: '复垦项目名称'
                        },
                        {
                            xtype: 'numbercolumn',
                            width: 140,
                            align: 'center',
                            dataIndex: 'fkxmgm',
                            text: '复垦项目规模（公顷）'
                        },
                        {
                            xtype: 'numbercolumn',
                            width: 126,
                            align: 'center',
                            dataIndex: 'kcrgm',
                            text: '可出让规模（公顷）'
                        },
                        {
                            xtype: 'numbercolumn',
                            width: 125,
                            align: 'center',
                            dataIndex: 'bccrgm',
                            text: '本次出让规模(公顷)'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 80,
                            align: 'center',
                            dataIndex: 'crzt',
                            text: '审核状态'
                        },
                        {
                            xtype: 'gridcolumn',
                            align: 'center',
                            dataIndex: 'crbz',
                            text: '备注',
                            tooltip: '备注信息将反馈给申让方'
                        }
                    ],
                    viewConfig: {
                        cls: 'x-grid3-row TD'
                    },
                    plugins: [
                        Ext.create('Ext.grid.plugin.CellEditing', {

                        })
                    ],
                    features: [
                        {
                            ftype: 'grouping'
                        }
                    ]
                }
            ],
            dockedItems: [
                {
                    xtype: 'pagingtoolbar',
                    dock: 'bottom',
                    width: 360,
                    displayInfo: true,
                    store: 'zbcrsh'
                }
            ]
        });

        me.callParent(arguments);
    }

});