/*
 * File: app/view/MyPanel16.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyPanel16', {
    extend: 'Ext.panel.Panel',

    height: 500,
    width: 557,
    layout: {
        type: 'border'
    },
    title: '交易态势异常监测',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'datefield',
                            width: 179,
                            fieldLabel: '起始日期',
                            labelWidth: 60,
                            enforceMaxLength: false,
                            useStrict: false
                        },
                        {
                            xtype: 'datefield',
                            width: 189,
                            fieldLabel: '结束日期',
                            labelWidth: 60
                        },
                        {
                            xtype: 'button',
                            text: '查询'
                        },
                        {
                            xtype: 'button',
                            text: '参数设置'
                        },
                        {
                            xtype: 'button',
                            text: '导出报告'
                        }
                    ]
                }
            ],
            items: [
                {
                    xtype: 'chart',
                    region: 'west',
                    width: 274,
                    animate: true,
                    insetPadding: 20,
                    series: [
                        {
                            type: 'pie',
                            label: {
                                field: 'x',
                                display: 'rotate',
                                contrast: true,
                                font: '12px Arial'
                            },
                            showInLegend: true,
                            angleField: 'y'
                        }
                    ]
                },
                {
                    xtype: 'gridpanel',
                    region: 'south',
                    height: 200,
                    title: '交易态势异常分析列表',
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            width: 112,
                            dataIndex: 'string',
                            text: '异常类型'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 345,
                            dataIndex: 'string',
                            text: '异常详情'
                        },
                        {
                            xtype: 'datecolumn',
                            width: 94,
                            dataIndex: 'date',
                            text: '出现时间'
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'pagingtoolbar',
                            dock: 'bottom',
                            width: 360,
                            displayInfo: true
                        }
                    ]
                },
                {
                    xtype: 'chart',
                    region: 'east',
                    width: 281,
                    animate: true,
                    insetPadding: 20,
                    axes: [
                        {
                            type: 'Category',
                            fields: [
                                'x'
                            ],
                            title: 'Category Axis',
                            position: 'bottom'
                        },
                        {
                            type: 'Numeric',
                            fields: [
                                'y'
                            ],
                            title: 'Numeric Axis',
                            position: 'left'
                        }
                    ],
                    series: [
                        {
                            type: 'column',
                            label: {
                                display: 'insideEnd',
                                field: 'y',
                                color: '#333',
                                'text-anchor': 'middle'
                            },
                            xField: 'x',
                            yField: 'y'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});