/*
 * File: app/view/quotaSimpleSearch.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.quotaSimpleSearch', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.quotaSimpleSearch',

    requires: [
        'Ext.form.Panel',
        'Ext.form.field.Text',
        'Ext.button.Button',
        'Ext.grid.Panel',
        'Ext.grid.View',
        'Ext.grid.column.Column',
        'Ext.toolbar.Paging'
    ],

    autoScroll: true,
    layout: 'border',
    title: '建设指标',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    region: 'north',
                    height: 56,
                    bodyPadding: 10,
                    title: '',
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'textfield',
                            margin: '',
                            width: 420,
                            fieldLabel: '',
                            hideLabel: true
                        },
                        {
                            xtype: 'button',
                            margin: 5,
                            width: 70,
                            text: '检索'
                        },
                        {
                            xtype: 'button',
                            margin: 5,
                            width: 70,
                            text: '高级检索'
                        }
                    ]
                },
                {
                    xtype: 'gridpanel',
                    flex: 1,
                    region: 'center',
                    title: '',
                    forceFit: true,
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            text: '检索结果：'
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'pagingtoolbar',
                            dock: 'bottom',
                            width: 360,
                            displayInfo: true
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});