/*
 * File: app/view/wdsglb.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.wdsglb', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.wdsglb',

    requires: [
        'Ext.grid.Panel',
        'Ext.grid.RowNumberer',
        'Ext.form.field.Number',
        'Ext.grid.View',
        'Ext.grid.plugin.CellEditing',
        'Ext.toolbar.Paging',
        'Ext.form.Label',
        'Ext.toolbar.Fill'
    ],

    height: 615,
    width: 950,
    layout: 'fit',
    title: '<font size=\'2.5px\'>我的指标</font>',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'gridpanel',
                    cls: 'x-grid3-row',
                    height: 211,
                    id: '',
                    autoScroll: true,
                    title: '',
                    store: 'zbgmstore',
                    columns: [
                        {
                            xtype: 'rownumberer',
                            width: 37,
                            align: 'center',
                            text: '序号'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 103,
                            align: 'center',
                            dataIndex: 'zbpcbh',
                            text: '指标批次编号'
                        },
                        {
                            xtype: 'gridcolumn',
                            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                return value+'公顷';
                            },
                            width: 96,
                            align: 'center',
                            dataIndex: 'dwed',
                            text: '单位额度'
                        },
                        {
                            xtype: 'gridcolumn',
                            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                return value+'张';
                            },
                            width: 72,
                            align: 'center',
                            dataIndex: 'sl',
                            text: '总数量'
                        },
                        {
                            xtype: 'gridcolumn',
                            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                return record.get('dwed')*record.get('sl')+'公顷';
                            },
                            width: 80,
                            align: 'center',
                            text: '总额度'
                        },
                        {
                            xtype: 'gridcolumn',
                            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                return value+'张';
                            },
                            width: 78,
                            align: 'center',
                            dataIndex: 'sgsl',
                            text: '申购数量',
                            editor: {
                                xtype: 'numberfield',
                                allowBlank: false,
                                blankText: '不能为空',
                                regex: /^[0-9]*[1-9][0-9]*$/,
                                regexText: '申购数量至少为1'
                            }
                        },
                        {
                            xtype: 'gridcolumn',
                            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                return record.get('dwed')*record.get('sgsl')+'公顷';
                            },
                            width: 97,
                            align: 'center',
                            text: '申购总额'
                        },
                        {
                            xtype: 'gridcolumn',
                            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                if(value==1)
                                return "申请阶段";
                                if(value==2)
                                return "交保证金阶段";
                                if(value==3)
                                return "竞价阶段";
                                if(value==4)
                                return "网签阶段";
                                if(value==5)
                                return "网备阶段";
                            },
                            width: 96,
                            align: 'center',
                            dataIndex: 'dqhj',
                            text: '当前环节'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 88,
                            align: 'center',
                            dataIndex: 'pczt',
                            text: '状态'
                        },
                        {
                            xtype: 'gridcolumn',
                            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                var dqhj=record.get('dqhj');
                                var pczt=record.get('pczt');
                                var zt;
                                switch(pczt)
                                {
                                    case '尚未提交':
                                    zt='1';
                                    break;
                                    case '待审核':
                                    zt='2';
                                    break;
                                    case '通过':
                                    zt='3';
                                    break;
                                    case '未通过':
                                    zt='4';
                                    break;
                                    case '尚未开始':
                                    zt='1';
                                    break;
                                    case '正在进行':
                                    zt='2';
                                    break;
                                    case '中标':
                                    zt='3';
                                    break;
                                    case '未中标':
                                    zt='4';
                                    break;
                                    case '未签':
                                    zt='1';
                                    break;
                                    case '已签':
                                    zt='2';
                                    break;
                                    case '尚未备案':
                                    zt='1';
                                    break;
                                    case '完成备案':
                                    zt='2';
                                    break;

                                    default:
                                    break;

                                }
                                var cz=dqhj+zt;
                                switch(cz)
                                {
                                    case '11':
                                    return "<button >提交订单</button>";
                                    case '12':
                                    return "<button disabled='disabled'>提交订单</button>";
                                    case '13':
                                    return "<button disabled='disabled'>提交订单</button>";
                                    case '14':
                                    return "<button >提交订单</button>";
                                    case '21':
                                    return "<button >交保证金</button>";
                                    case '22':
                                    return "<button disabled='disabled' >交保证金</button>";
                                    case '23':
                                    return "<button disabled='disabled' >交保证金</button>";
                                    case '24':
                                    return "<button disabled='disabled' >交保证金核</button>";


                                    case '31':
                                    return "<button>开始竞价</button>";
                                    case '32':
                                    return "<button>开始竞价</button>";
                                    case '33':
                                    return "<button>开始竞价</button>";
                                    case '34':
                                    return "<button>开始竞价</button>";

                                    case '41':
                                    return "<button>网上签约</button>";
                                    case '42':
                                    return "<button>网上签约</button>";
                                    case '51':
                                    return "<button '>申请网备</button>";
                                    case '52':
                                    return "<button disabled='disabled'>申请网备</button>";
                                }

                            },
                            width: 80,
                            align: 'center',
                            text: '操作',
                            tooltip: '点击进入相应的购买环节'
                        },
                        {
                            xtype: 'gridcolumn',
                            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                return '<font color=red>'+value+'</font>';
                            },
                            width: 120,
                            align: 'center',
                            dataIndex: 'pcbz',
                            text: '备注'
                        }
                    ],
                    viewConfig: {
                        getRowClass: function(record, rowIndex, rowParams, store) {

                            var dqhj=record.get('dqhj');
                            var pczt=record.get('pczt');
                            var zt;
                            switch(pczt)
                            {
                                case '尚未提交':
                                zt='1';
                                break;
                                case '待审核':
                                zt='2';
                                break;
                                case '通过':
                                zt='3';
                                break;
                                case '未通过':
                                zt='4';
                                break;
                                case '尚未开始':
                                zt='1';
                                break;
                                case '正在进行':
                                zt='2';
                                break;
                                case '中标':
                                zt='3';
                                break;
                                case '未中标':
                                zt='4';
                                break;
                                case '未签':
                                zt='1';
                                break;
                                case '已签':
                                zt='2';
                                break;
                                case '尚未备案':
                                zt='1';
                                break;
                                case '完成备案':
                                zt='2';
                                break;

                                default:
                                break;

                            }
                            var cz=dqhj+zt;
                            switch(cz)
                            {
                                case '11':
                                return 'oper';
                                case '12':
                                return 'wait';
                                case '13':
                                return 'oper';
                                case '14':
                                return 'oper';
                                case '21':
                                return 'oper';
                                case '22':
                                return 'wait';
                                case '23':
                                return 'oper';
                                case '24':
                                return 'oper';
                                case '31':
                                return 'wait';
                                case '32':
                                return 'oper';
                                case '33':
                                return 'wait';
                                case '34':
                                return 'wait';
                                case '41':
                                return 'oper';
                                case '42':
                                return '';
                                case '51':
                                return 'oper';
                                case '52':
                                return '';

                            }
                        },
                        cls: 'x-grid3-row',
                        listeners: {
                            cellclick: {
                                fn: me.onViewCellClick,
                                scope: me
                            }
                        }
                    },
                    plugins: [
                        Ext.create('Ext.grid.plugin.CellEditing', {

                        })
                    ]
                }
            ],
            dockedItems: [
                {
                    xtype: 'pagingtoolbar',
                    dock: 'bottom',
                    width: 360,
                    displayInfo: true,
                    store: 'zbgmstore'
                },
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    height: 44,
                    items: [
                        {
                            xtype: 'label',
                            style: {
                                fontSize: '12px',
                                color: 'red'
                            },
                            text: '在审核通过后不能更改订单内容和相关凭证,如果未通过审核在规定时间前可重新提交相关信息'
                        },
                        {
                            xtype: 'tbfill'
                        },
                        {
                            xtype: 'label',
                            style: {
                                fontSize: '12px',
                                cursor: 'pointer',
                                color: 'blue'
                            },
                            width: 81,
                            text: '返回公告列表',
                            listeners: {
                                click: {
                                    fn: me.onLabelClick,
                                    element: 'el',
                                    scope: me
                                }
                            }
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onViewCellClick: function(tableview, td, cellIndex, record, tr, rowIndex, e, eOpts) {
        if(cellIndex==9)
        {
            var panel=Ext.getCmp('contentPanel');
            var p;
            var dqhj=record.get('dqhj');
            var pczt=record.get('pczt');
            var zt;
            switch(pczt)
            {
                case '尚未提交':
                zt='1';
                break;
                case '待审核':
                zt='2';
                break;
                case '通过':
                zt='3';
                break;
                case '未通过':
                zt='4';
                break;
                case '尚未开始':
                zt='1';
                break;
                case '正在进行':
                zt='2';
                break;
                case '中标':
                zt='3';
                break;
                case '未中标':
                zt='4';
                break;
                case '未签':
                zt='1';
                break;
                case '已签':
                zt='2';
                break;
                case '尚未备案':
                zt='1';
                break;
                case '完成备案':
                zt='2';
                break;

                default:
                break;

            }
            var cz=dqhj+zt;
            switch(cz)
            {
                case '11':
                var cpanel=Ext.getCmp('contentPanel');
                var scpz=Ext.widget('scpz');
                scpz.items.get(5).disable();
                Ext.getCmp('yyzzpcbh').setValue(record.get('zbpcbh'));
                Ext.getCmp('nspzpcbh').setValue(record.get('zbpcbh'));
                Ext.getCmp('zzdmpcbh').setValue(record.get('zbpcbh'));
                Ext.getCmp('sfzmpcbh').setValue(record.get('zbpcbh'));
                Ext.getCmp('bh').setValue(record.get('zbpcbh'));
                cpanel.removeAll();
                cpanel.add(scpz);
                break;
                case '12':
                Ext.MessageBox.confirm('提示','该订单已经提交正在等待管理员审核，您确定要重新提交吗？',function(btn){
                    if(btn=='yes')
                    {
                        Ext.Ajax.request(
                        {
                            url:'tjdd',
                            method:'post',
                            headers:{

                                'Content-Type':'application/json'
                            },
                            params:Ext.encode(record.getData()),
                            success:function(response){
                                // var panel=Ext.getCmp('contentPanel');
                                // var p=Ext.widget('scpz');
                                //Ext.getCmp('yyzzpcbh').setValue(record.get('zbpcbh'));
                                // Ext.getCmp('nspzpcbh').setValue(record.get('zbpcbh'));
                                //Ext.getCmp('zzdmpcbh').setValue(record.get('zbpcbh'));
                                // Ext.getCmp('sfzmpcbh').setValue(record.get('zbpcbh'));
                                // Ext.getCmp('bh').setValue(record.get('zbpcbh'));
                                // panel.removeAll();
                                //panel.add(p);
                            },

                            failure:function(){
                                //Ext.MessageBox.alert('错误','操作失败！');
                            }

                        });
                    }
                });

                break;
                case '13':
                //return "<button disabled='disabled'>提交订单</button>";
                break;
                case '14':
                Ext.Ajax.request(
                {
                    url:'tjdd',
                    method:'post',
                    headers:{

                        'Content-Type':'application/json'
                    },
                    params:Ext.encode(record.getData()),
                    success:function(response){
                        var panel=Ext.getCmp('contentPanel');
                        var p=Ext.widget('scpz');
                        Ext.getCmp('yyzzpcbh').setValue(record.get('zbpcbh'));
                        Ext.getCmp('nspzpcbh').setValue(record.get('zbpcbh'));
                        Ext.getCmp('zzdmpcbh').setValue(record.get('zbpcbh'));
                        Ext.getCmp('sfzmpcbh').setValue(record.get('zbpcbh'));
                        Ext.getCmp('bh').setValue(record.get('zbpcbh'));
                        panel.removeAll();
                        panel.add(p);
                    },

                    failure:function(){
                        //Ext.MessageBox.alert('错误','操作失败！');
                    }

                });
                break;
                case '21':

                p=Ext.widget('jbzj');
                p.items.get(0).loadRecord(record);

                p.items.get(0).getComponent('sgze').setValue(Ext.Number.from(record.get('sgsl'),1)*Ext.Number.from(record.get('dwed'),1)+'公顷');
                p.items.get(0).getComponent('yjbzj').setValue(Ext.Number.from(record.get('sgsl'),1)*Ext.Number.from(record.get('dwed'),1)*0.05+'万元');
                panel.removeAll();
                panel.add(p);
                break;
                case '22':
                //var panel=Ext.getCmp('contentPanel');
                p=Ext.widget('jbzj');
                panel.removeAll();
                panel.add(p);
                break;
                case '23':
                break;
                case '24':
                //var panel=Ext.getCmp('contentPanel');
                p=Ext.widget('jbzj');
                panel.removeAll();
                panel.add(p);
                break;


                case '31':
                p=Ext.widget('pmjjclient');
                panel.removeAll();
                panel.add(p);

                var form=Ext.getCmp('jpxxclient');
                Ext.getCmp('sgslclient').setValue(record.get('sgsl'));

                form.load({
                    url:'getjpxx',
                    params:{zbpcbh:record.get('zbpcbh')},
                    success:function(form,action){

                        //Ext.MessageBox.alert('提示','设置成功');

                        runner.stopAll();
                        var dif=action.result.dif;
                        //alert(dif);
                        var day=parseInt(dif/(24*3600*1000));
                        var hour=parseInt(dif/(3600*1000))-day*24;
                        var minute=parseInt(dif/(60*1000))-day*24*60-hour*60;
                        var second=parseInt(dif/1000)-day*24*3600-hour*3600-minute*60;

                        var djs=Ext.getCmp('pcqtclient');

                        var task =runner.newTask({
                            run: function()
                            {
                                var flag=1;
                                if(second>0)
                                {
                                    second=second-1;
                                }
                                else
                                {
                                    if(minute>0)
                                    {

                                        second=59;
                                        minute=minute-1;
                                    }
                                    else
                                    {
                                        if(hour>0)
                                        {
                                            minute=59;
                                            hour=hour-1;
                                        }
                                        else
                                        {
                                            if(day>0)
                                            {
                                                hour=23;
                                                day=day-1;
                                            }
                                            else
                                            {
                                                djs.setValue('正在进行');
                                                Ext.getCmp('pcztclient').setValue('正在进行');
                                                flag=0;
                                            }
                                        }
                                    }

                                }
                                if(flag==1)
                                {//alert(second);
                                    djs.setValue(day+'天'+hour+'小时'+minute+'分'+second+'秒');
                                }

                            },
                            interval:1000
                        }

                        );
                        task.start();

                    }

                });


                break;

                case '32':
                p=Ext.widget('pmjjclient');
                panel.removeAll();
                panel.add(p);
                var form=Ext.getCmp('jpxxclient');
                Ext.getCmp('sgslclient').setValue(record.get('sgsl'));
                form.load({
                    url:'getjpxx',
                    params:{zbpcbh:record.get('zbpcbh')},
                    success:function(form,action){

                        Ext.MessageBox.alert('提示','设置成功');
                        runner.stopAll();
                        var dif=action.result.dif;
                        var day=parseInt(dif/(24*3600*1000));
                        var hour=parseInt(dif/(3600*1000))-day*24;
                        var minute=parseInt(dif/(60*1000))-day*24*60-hour*60;
                        var second=parseInt(dif/1000)-day*24*3600-hour*3600-minute*60;

                        var djs=Ext.getCmp('pcqtclient');

                        var task =runner.newTask({
                            run: function()
                            {
                                var flag=1;
                                if(second>0)
                                {
                                    second=second-1;
                                }
                                else
                                {
                                    if(minute>0)
                                    {

                                        second=59;
                                        minute=minute-1;
                                    }
                                    else
                                    {
                                        if(hour>0)
                                        {
                                            minute=59;
                                            hour=hour-1;
                                        }
                                        else
                                        {
                                            if(day>0)
                                            {
                                                hour=23;
                                                day=day-1;
                                            }
                                            else
                                            {
                                                djs.setValue('正在进行');
                                                Ext.getCmp('pcztclient').setValue('正在进行');
                                                flag=0;
                                            }
                                        }
                                    }

                                }
                                if(flag==1)
                                {//alert(second);
                                    djs.setValue(day+'天'+hour+'小时'+minute+'分'+second+'秒');
                                }

                            },
                            interval:1000
                        }

                        );
                        task.start();

                    }

                });

                break;
                case '33':
                break;
                case '34':
                break;

                case '41':
                p=Ext.widget('wqclient');
                panel.removeAll();
                Ext.getCmp('wqzbpcbh').setValue(record.get('zbpcbh'));
                var ht=Ext.getCmp('wqht');
                var htContent="<iframe src='"+record.get('htwz')+"' width=100% height=100%></iframe>";
                //var htContent="<iframe src='"+"ht/admin.html"+"' width=100% height=100%></iframe>";
                ht.html=htContent;
                var str=record.get('htwz');
        		var strs= new Array(2);
        			strs=str.split("."); //字符分割
               Ext.getCmp('download_url').setValue(strs[0]+'.doc');
                // alert(htContent);
                panel.add(p);
                break;

                case '42':
                p=Ext.widget('wqclient');
                panel.removeAll();

                ht2=Ext.getCmp('wqht');
                 Ext.getCmp('wqzbpcbh').setValue(record.get('zbpcbh'));
                var ht2=Ext.getCmp('wqht');
                var htContent2="<iframe src='"+record.get('htwz')+"' width=100% height=100%></iframe>";
                //var htContent="<iframe src='"+"ht/admin.html"+"' width=100% height=100%></iframe>";
                ht2.html=htContent;
                var str1=record.get('htwz');
        		var strs1= new Array(2);
        			strs1=str1.split("."); //字符分割
               Ext.getCmp('download_url').setValue(strs1[0]+'.doc');
                panel.add(p);
                break;
                case '51':
                p=Ext.widget('wbclient');
                Ext.getCmp('wbpcbh').setValue(record.get('zbpcbh'));
                panel.removeAll();
                panel.add(p);
                break;
                case '52':
                p=Ext.widget('wbclient');
                Ext.getCmp('wbpcbh').setValue(record.get('zbpcbh'));
                panel.removeAll();
                panel.add(p);
                break;
            }

        }
    },

    onLabelClick: function(label) {
        var gmstore=Ext.StoreMgr.get('zbgmstore');
        var ggstore=Ext.StoreMgr.get('zbgglbstore');
        var panel=Ext.getCmp('contentPanel');
        /*
        gmstore.each(function(rec){
        // zbpcbhs.push(gmstore.get('zbpcbh'));
        var zbpcbh=rec.get('zbpcbh');
        //alert(zbpcbh);
        ggstore.getAt(ggstore.find('zbpcbh',zbpcbh)).set('pcqt','yd');
        //alert( ggstore.getAt(ggstore.find('zbpcbh',zbpcbh)).get('pcqt'));
        //rec.setValue('pcqt','yd');//已订
        //ggstore.removeAt(ggstore.find('zbpcbh',rec.get('zbpcbh')));
        });
        */
        ggstore.clearFilter();

        ggstore.filter('pcqt','wd');
        var zbsg=Ext.widget('zbsq');
        var wdzb=Ext.widget('wdsglb');
        panel.removeAll();
        panel.add(zbsg);
        panel.add(wdzb);
    }

});