/*
 * File: app/view/wqclient.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.wqclient', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.wqclient',

    requires: [
        'Ext.form.Panel',
        'Ext.toolbar.Toolbar',
        'Ext.form.field.Display',
        'Ext.toolbar.Spacer',
        'Ext.button.Button',
        'Ext.form.field.Text',
        'Ext.Img',
        'Ext.form.Label'
    ],

    height: 708,
    width: 884,
    layout: 'absolute',
    title: '<font size=\'2.5px\'>网签</font>',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    x: 30,
                    y: 30,
                    border: false,
                    height: 550,
                    id: 'wqht',
                    width: 710,
                    autoScroll: true,
                    layout: 'absolute',
                    bodyPadding: 10,
                    title: '',
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            x: -14,
                            y: -32,
                            dock: 'top',
                            height: 30,
                            items: [
                                {
                                    xtype: 'displayfield',
                                    id: 'wqzbpcbh',
                                    fieldLabel: '批次编号',
                                    value: '01'
                                },
                                {
                                    xtype: 'tbspacer',
                                    height: 10,
                                    width: 65
                                },
                                {
                                    xtype: 'button',
                                    handler: function(button, event) {
                                        window.location = Ext.getCmp('download_url').getValue();
                                    },
                                    id: 'wqsave',
                                    width: 77,
                                    text: '保存'
                                },
                                {
                                    xtype: 'textfield',
                                    hidden: true,
                                    id: 'download_url',
                                    fieldLabel: 'Label'
                                },
                                {
                                    xtype: 'tbspacer',
                                    height: 10,
                                    width: 65
                                },
                                {
                                    xtype: 'button',
                                    handler: function(button, event) {
                                        var zbpcbh=Ext.getCmp('wqzbpcbh').getValue();
                                        Ext.Ajax.request(
                                        {
                                            url:'updateToWb',
                                            method:'get',
                                            headers:{

                                                'Content-Type':'application/json'
                                            },
                                            params:{'zbpcbh':Ext.getCmp('wqzbpcbh').getValue()},
                                            success:function(response){
                                                // Ext.StoreMgr.get('zbgmstore').add(Ext.getCmp('tjdd').getValues());
                                                var store=Ext.StoreMgr.get('zbgmstore');

                                                var n=store.find('zbpcbh',zbpcbh);
                                                //alert(n);
                                                store.getAt(n).set('dqhj','5');
                                                store.getAt(n).set('pczt','尚未备案');
                                                Ext.MessageBox.alert('提示','请在7个工作日内交纳合同价款并申请网上备案',function(){
                                                    var panel=Ext.getCmp('contentPanel');

                                                    var zbsg=Ext.widget('wdsglb');
                                                    panel.removeAll();
                                                    panel.add(zbsg);

                                                });

                                            },

                                            failure:function(){
                                                //Ext.MessageBox.alert('错误','操作失败！');
                                            }

                                        });

                                    },
                                    width: 54,
                                    text: '同意'
                                }
                            ]
                        }
                    ]
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    x: 152,
                    y: 11,
                    dock: 'top',
                    height: 50,
                    items: [
                        {
                            xtype: 'image',
                            height: 40,
                            width: 569,
                            src: 'images/lc5.png'
                        },
                        {
                            xtype: 'label',
                            height: 12,
                            style: {
                                fontSize: '12px',
                                cursor: 'pointer',
                                color: 'blue'
                            },
                            width: 84,
                            text: '返回订单列表',
                            listeners: {
                                click: {
                                    fn: me.onLabelClick11,
                                    element: 'el',
                                    scope: me
                                }
                            }
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onLabelClick11: function(label) {

        var panel=Ext.getCmp('contentPanel');

        var zbsg=Ext.widget('wdsglb');
        panel.removeAll();
        panel.add(zbsg);

    }

});