/*
 * File: app/view/wqgl.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.wqgl', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.wqgl',

    requires: [
        'Ext.grid.column.Action',
        'Ext.grid.View',
        'Ext.toolbar.Toolbar',
        'Ext.Img',
        'Ext.form.Label',
        'Ext.form.field.Text'
    ],

    height: 572,
    width: 995,
    title: '<font size=\'2.5px\'>网签</font>',
    store: 'zbgmstore',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            columns: [
                {
                    xtype: 'gridcolumn',
                    align: 'center',
                    dataIndex: 'zbpcbh',
                    text: '批次编号'
                },
                {
                    xtype: 'gridcolumn',
                    align: 'center',
                    dataIndex: 'userid',
                    text: '用户名'
                },
                {
                    xtype: 'gridcolumn',
                    align: 'center',
                    dataIndex: 'dwed',
                    text: '单位额度'
                },
                {
                    xtype: 'gridcolumn',
                    align: 'center',
                    dataIndex: 'sgsl',
                    text: '购买数量'
                },
                {
                    xtype: 'gridcolumn',
                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                        return record.get('sgsl')*record.get('dwed');
                    },
                    align: 'center',
                    dataIndex: 'string',
                    text: '购买总额'
                },
                {
                    xtype: 'gridcolumn',
                    align: 'center',
                    dataIndex: 'zbdj',
                    text: '成交单价'
                },
                {
                    xtype: 'gridcolumn',
                    align: 'center',
                    dataIndex: 'yfkze',
                    text: '成交总价'
                },
                {
                    xtype: 'actioncolumn',
                    handler: function(view, rowIndex, colIndex, item, e, record, row) {
                        Ext.Ajax.request(
                        {
                            url:'scht',
                            method:'post',
                            headers:{

                                'Content-Type':'application/json'
                            },
                            params:Ext.encode(record.getData()),
                            success:function(response){
                                Ext.MessageBox.alert('信息','合同生成成功');

                                var result=Ext.decode(response.responseText);
                                //alert(result.htwz);
                                record.set('htwz',result.htwz);
                                //Ext.MessageBox.alert('信息','发布成功',function(btn){
                                //alert(result.zbpcbh);
                                //record.set('zbpcbh',result.zbpcbh);
                                //record.commit();
                                //});
                            },
                            failure:function(){
                                //Ext.MessageBox.alert('错误','操作失败！');
                            }

                        }
                        );
                    },
                    id: 'schtbtn',
                    width: 85,
                    align: 'center',
                    dataIndex: 'string',
                    icon: 'images/ht.png',
                    listeners: {
                        afterrender: {
                            fn: me.onActioncolumnAfterRender,
                            scope: me
                        }
                    }
                },
                {
                    xtype: 'actioncolumn',
                    handler: function(view, rowIndex, colIndex, item, e, record, row) {
                        window.open (record.get('htwz'));
                    },
                    id: 'wqckht',
                    width: 83,
                    align: 'center',
                    dataIndex: 'htwz',
                    icon: 'images/ck.png',
                    listeners: {
                        afterrender: {
                            fn: me.onActioncolumnAfterRender1,
                            scope: me
                        }
                    }
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    height: 38,
                    items: [
                        {
                            xtype: 'image',
                            height: 35,
                            width: 540,
                            src: 'images/step5.png'
                        },
                        {
                            xtype: 'label',
                            style: {
                                fontSize: '12px',
                                cursor: 'pointer',
                                color: 'blue'
                            },
                            width: 100,
                            text: '返回管理列表',
                            listeners: {
                                click: {
                                    fn: me.onLabelClick1111,
                                    element: 'el',
                                    scope: me
                                }
                            }
                        },
                        {
                            xtype: 'textfield',
                            hidden: true,
                            id: 'wqglzbpcbh',
                            fieldLabel: 'Label'
                        }
                    ]
                }
            ],
            listeners: {
                activate: {
                    fn: me.onGridpanelActivate,
                    scope: me
                }
            }
        });

        me.callParent(arguments);
    },

    onActioncolumnAfterRender: function(component, eOpts) {
        Ext.getCmp('schtbtn').setText('生成合同');
    },

    onActioncolumnAfterRender1: function(component, eOpts) {
        Ext.getCmp('wqckht').setText('查看合同');
    },

    onLabelClick1111: function(label) {
        var myTabPanel = Ext.getCmp('htglTabPanelMain');
        myTabPanel.removeAll(true);
        myTabPanel.add(Ext.widget('fbjgck'));
    },

    onGridpanelActivate: function(component, eOpts) {
        var store=Ext.StoreMgr.get('zbgmstore');
        store.clearFilter();
        store.filter('zbpcbh',Ext.getCmp('wqglzbpcbh').getValue());
        store.filter('dqhj',4);
    }

});