/*
 * File: app/view/zbcrshwin.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.zbcrshwin', {
    extend: 'Ext.window.Window',
    alias: 'widget.zbcrshwin',

    requires: [
        'Ext.form.Panel',
        'Ext.form.field.TextArea',
        'Ext.button.Button'
    ],

    height: 413,
    width: 620,
    layout: 'fit',
    title: '',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    layout: 'absolute',
                    bodyPadding: 10,
                    title: '',
                    items: [
                        {
                            xtype: 'textareafield',
                            x: 50,
                            y: 230,
                            width: 520,
                            fieldLabel: '审核意见',
                            name: 'crbz'
                        },
                        {
                            xtype: 'button',
                            x: 350,
                            y: 330,
                            width: 90,
                            text: '不通过',
                            listeners: {
                                click: {
                                    fn: me.onButtonClick1,
                                    scope: me
                                }
                            }
                        },
                        {
                            xtype: 'button',
                            x: 170,
                            y: 330,
                            width: 90,
                            text: '通过',
                            listeners: {
                                click: {
                                    fn: me.onButtonClick,
                                    scope: me
                                }
                            }
                        },
                        {
                            xtype: 'textfield',
                            x: 340,
                            y: 170,
                            fieldLabel: '本次出让规模',
                            name: 'bccrgm'
                        },
                        {
                            xtype: 'textfield',
                            x: 50,
                            y: 170,
                            fieldLabel: '可出让规模',
                            name: 'kcrgm'
                        },
                        {
                            xtype: 'textfield',
                            x: 340,
                            y: 100,
                            fieldLabel: '复垦项目规模',
                            name: 'fkxmgm'
                        },
                        {
                            xtype: 'textfield',
                            x: 50,
                            y: 100,
                            fieldLabel: '复垦项目位置',
                            name: 'fkxmbwz'
                        },
                        {
                            xtype: 'textfield',
                            x: 50,
                            y: 30,
                            fieldLabel: '复垦项目编号',
                            name: 'fkxmbh'
                        },
                        {
                            xtype: 'textfield',
                            x: 340,
                            y: 30,
                            fieldLabel: '复垦项目名称',
                            name: 'fkxmmc'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onButtonClick1: function(button, e, eOpts) {
        this.close();
    },

    onButtonClick: function(button, e, eOpts) {
        this.close();
    }

});