/*
 * File: app/view/zblbfb.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.zblbfb', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.zblbfb',

    requires: [
        'Ext.Img',
        'Ext.grid.Panel',
        'Ext.form.field.Number',
        'Ext.form.field.ComboBox',
        'Ext.grid.column.Date',
        'Ext.form.field.Date',
        'Ext.grid.View',
        'Ext.grid.column.Action',
        'Ext.button.Button',
        'Ext.form.Label',
        'Ext.selection.CheckboxModel',
        'Ext.toolbar.Paging',
        'Ext.grid.plugin.CellEditing'
    ],

    height: 344,
    width: 957,
    layout: 'fit',
    title: '指标发布',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    height: 40,
                    items: [
                        {
                            xtype: 'image',
                            height: 35,
                            width: 562,
                            src: 'images/step1.png'
                        }
                    ]
                }
            ],
            items: [
                {
                    xtype: 'gridpanel',
                    id: 'zbfb',
                    title: '',
                    store: 'zbgglbstore',
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {

                                if(value==null||value=='')
                                {
                                    return "编辑";
                                }
                                else
                                return value;
                            },
                            align: 'center',
                            dataIndex: 'zbpcbh',
                            text: '指标批次编号'
                        },
                        {
                            xtype: 'gridcolumn',
                            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                if(value==null||value=='')
                                {
                                    return "自动生成";
                                }
                                else
                                return value;
                            },
                            width: 89,
                            align: 'center',
                            text: '复垦项目编号'
                        },
                        {
                            xtype: 'gridcolumn',
                            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                if(value==null||value=='')
                                {
                                    return "编辑";
                                }
                                else
                                return value+'公顷/张';
                            },
                            width: 76,
                            align: 'center',
                            dataIndex: 'dwed',
                            text: '单位额度',
                            editor: {
                                xtype: 'numberfield',
                                allowBlank: false,
                                blankText: '不能为空',
                                regex: /^(\d*\.)?\d+$/,
                                regexText: '只能输入数字'
                            }
                        },
                        {
                            xtype: 'gridcolumn',
                            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                if(value==null||value=='')
                                {
                                    return "编辑";
                                }
                                else
                                return value+'张';
                            },
                            width: 71,
                            align: 'center',
                            dataIndex: 'sl',
                            text: '数量',
                            editor: {
                                xtype: 'numberfield',
                                allowBlank: false,
                                blankText: '不能为空'
                            }
                        },
                        {
                            xtype: 'gridcolumn',
                            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                if(value==null||value=='')
                                {
                                    return "编辑";
                                }
                                else
                                return value;
                            },
                            width: 74,
                            align: 'center',
                            dataIndex: 'jylx',
                            text: '交易类型',
                            editor: {
                                xtype: 'combobox',
                                value: '竞拍',
                                allowBlank: false,
                                blankText: '不能为空',
                                emptyText: '请选择',
                                editable: false,
                                queryMode: 'local',
                                store: 'jylx',
                                valueField: 'text',
                                listeners: {
                                    change: {
                                        fn: me.onComboboxChange,
                                        scope: me
                                    }
                                }
                            }
                        },
                        {
                            xtype: 'gridcolumn',
                            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                if(value==null||value=='')
                                {
                                    return "编辑";
                                }
                                else
                                return value+'万元';
                            },
                            width: 79,
                            align: 'center',
                            dataIndex: 'dj',
                            text: '底价',
                            editor: {
                                xtype: 'numberfield',
                                allowBlank: false
                            }
                        },
                        {
                            xtype: 'datecolumn',
                            width: 88,
                            align: 'center',
                            dataIndex: 'sqjzrq',
                            text: '申请截止日期',
                            format: 'Y-m-d',
                            editor: {
                                xtype: 'datefield',
                                allowBlank: false,
                                blankText: '不能为空'
                            }
                        },
                        {
                            xtype: 'datecolumn',
                            width: 88,
                            align: 'center',
                            dataIndex: 'jjksrq',
                            text: '竞价开始日期',
                            format: 'Y-m-d',
                            editor: {
                                xtype: 'datefield'
                            }
                        },
                        {
                            xtype: 'datecolumn',
                            width: 90,
                            align: 'center',
                            dataIndex: 'jjjsrq',
                            text: '竞价结束日期',
                            format: 'Y-m-d',
                            editor: {
                                xtype: 'datefield'
                            }
                        },
                        {
                            xtype: 'actioncolumn',
                            width: 65,
                            align: 'center',
                            tooltip: '发布指标',
                            icon: 'images/fb.jpg',
                            items: [
                                {
                                    handler: function(view, rowIndex, colIndex, item, e, record, row) {
                                        var store=Ext.StoreMgr.get('zbgglbstore');
                                        record.set('pczt','尚未提交');
                                        Ext.Ajax.request(
                                        {
                                            url:'addfbzb',
                                            method:'post',
                                            headers:{

                                                'Content-Type':'application/json'
                                            },
                                            params:Ext.encode(record.getData()),
                                            success:function(response){
                                                var result=Ext.decode(response.responseText);
                                                Ext.MessageBox.alert('信息','发布成功',function(btn){
                                                    //alert(result.zbpcbh);
                                                    record.set('zbpcbh',result.zbpcbh);
                                                    record.commit();
                                                });
                                            },
                                            failure:function(){
                                                //Ext.MessageBox.alert('错误','操作失败！');
                                            }

                                        }
                                        );
                                    },
                                    icon: 'images/true.png',
                                    tooltip: '发布指标'
                                }
                            ],
                            listeners: {
                                afterrender: {
                                    fn: me.onActioncolumnAfterRender,
                                    scope: me
                                }
                            }
                        }
                    ],
                    viewConfig: {
                        cls: 'x-grid3-row',
                        minHeight: 200
                    },
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            height: 33,
                            items: [
                                {
                                    xtype: 'button',
                                    handler: function(button, event) {

                                        var store=Ext.StoreMgr.get('zbgglbstore');
                                        var r=Ext.widget('zbgglbmodel', {
                                            id: '',
                                            zbpcbh: '',
                                            dwed: '',
                                            sl: '',
                                            jylx: '',
                                            dj: '',
                                            fbrq: new Date(),
                                            sqjzrq: this.addDay(new Date(),10),
                                            bzjjzrq: '',
                                            jjksrq: '',
                                            jjjsrq: '',
                                            pczt: '',
                                            pcbz: '',
                                            pcqt: '',
                                            sfjs:'false',
                                            dqhj:1
                                        });
                                        //alert(r);

                                        store.add(r);


                                    },
                                    addDay: function(date,days) {

                                        var nd = new Date(date);
                                        nd = nd.valueOf();
                                        nd = nd + days * 24 * 60 * 60 * 1000;
                                        nd = new Date(nd);
                                        //alert(nd.getFullYear() + "年" + (nd.getMonth() + 1) + "月" + nd.getDate() + "日");
                                        var y = nd.getFullYear();
                                        var m = nd.getMonth()+1;
                                        var d = nd.getDate();
                                        if(m <= 9) m = "0"+m;
                                        if(d <= 9) d = "0"+d;
                                        var cdate = y+"-"+m+"-"+d;
                                        return cdate;

                                    },
                                    width: 80,
                                    text: '添加新指标'
                                },
                                {
                                    xtype: 'button',
                                    handler: function(button, event) {
                                        var store=Ext.StoreMgr.get('zbgglbstore');
                                        var grid=Ext.getCmp('zbfb');
                                        var sm = grid.getSelectionModel();
                                        //rowEditing.cancelEdit();
                                        store.remove(sm.getSelection());
                                        //if (store.getCount() > 0) {
                                        // sm.select(0);
                                        // }
                                    },
                                    width: 80,
                                    text: '删除指标'
                                },
                                {
                                    xtype: 'label',
                                    style: {
                                        fontSize: '12px',
                                        cursor: 'pointer',
                                        color: 'blue'
                                    },
                                    text: '查看发布结果',
                                    listeners: {
                                        click: {
                                            fn: me.onLabelClick,
                                            element: 'el',
                                            scope: me
                                        }
                                    }
                                }
                            ]
                        },
                        {
                            xtype: 'pagingtoolbar',
                            dock: 'bottom',
                            width: 360,
                            displayInfo: true,
                            store: 'zbgglbstore'
                        }
                    ],
                    selModel: Ext.create('Ext.selection.CheckboxModel', {

                    }),
                    plugins: [
                        Ext.create('Ext.grid.plugin.CellEditing', {
                            clicksToEdit: 1
                        })
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onComboboxChange: function(field, newValue, oldValue, eOpts) {
        var grid=Ext.getCmp('zbfb');
        var sm = grid.getSelectionModel();
        var record=sm.getSelection()[0];
        var lx=record.get('jylx');
        var sqjzrq=record.get('sqjzrq');
        var jjksrq;
        if(lx=='竞拍')
        {
            jjksrq=this.addDays(sqjzrq,3);
            record.set('jjksrq',jjksrq);
            record.set('jjjsrq',jjksrq);
        }
        if(lx=='挂牌')
        {
            jjksrq=this.addDays(new Date(),3);
            record.set('jjksrq',jjksrq);
            record.set('jjjsrq',this.addDays(sqjzrq,3));
        }
    },

    onActioncolumnAfterRender: function(component, eOpts) {
        component.setText('发布');
    },

    onLabelClick: function(label) {
        var myTabPanel = Ext.getCmp('htglTabPanelMain');
        myTabPanel.removeAll(true);
        myTabPanel.add(Ext.widget('fbjgck'));
    },

    addDays: function(date,days) {

        var nd = new Date(date);
           nd = nd.valueOf();
           nd = nd + days * 24 * 60 * 60 * 1000;
           nd = new Date(nd);
           //alert(nd.getFullYear() + "年" + (nd.getMonth() + 1) + "月" + nd.getDate() + "日");
        var y = nd.getFullYear();
        var m = nd.getMonth()+1;
        var d = nd.getDate();
        if(m <= 9) m = "0"+m;
        if(d <= 9) d = "0"+d;
        var cdate = y+"-"+m+"-"+d;
        return cdate;

    }

});