/*
 * File: app/view/zbshrk.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.zbshrk', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.zbshrk',

    requires: [
        'Ext.grid.Panel',
        'Ext.grid.column.Number',
        'Ext.grid.column.Action',
        'Ext.grid.View',
        'Ext.form.field.Text',
        'Ext.grid.plugin.CellEditing',
        'Ext.grid.feature.Grouping',
        'Ext.XTemplate',
        'Ext.toolbar.Paging'
    ],

    height: 497,
    id: 'zbshrk',
    width: 1118,
    autoScroll: true,
    layout: 'fit',
    title: '指标审核入库',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'gridpanel',
                    height: 250,
                    width: 400,
                    title: '',
                    columnLines: true,
                    store: 'zbcrsh',
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'crzbbh',
                            text: '指标编号'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'userid',
                            text: '用户名'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'fkxmbh',
                            text: '指标编号'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'fkxmmc',
                            text: '复垦项目名称'
                        },
                        {
                            xtype: 'numbercolumn',
                            dataIndex: 'fkxmgm',
                            text: '指标总面积'
                        },
                        {
                            xtype: 'numbercolumn',
                            dataIndex: 'kcrgm',
                            text: '剩余面积'
                        },
                        {
                            xtype: 'numbercolumn',
                            dataIndex: 'bccrgm',
                            text: '本次出让面积'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 71,
                            dataIndex: 'crzt',
                            text: '审核状态'
                        },
                        {
                            xtype: 'actioncolumn',
                            handler: function(view, rowIndex, colIndex, item, e, record, row) {
                                var qszm=Ext.widget('qszm');
                                qszm.items.get(0).setSrc('http://localhost:8080/sell/'+record.get('qspzwz')+'.jpg');
                                //alert('http://localhost:8080/sell/'+record.get('qspzwz')+'.jpg');
                                qszm.show();
                            },
                            width: 70,
                            align: 'center',
                            dataIndex: 'qspzwz',
                            tooltip: '查看指标凭证',
                            icon: 'images/cktp.png',
                            listeners: {
                                afterrender: {
                                    fn: me.onDddddAfterRender,
                                    scope: me
                                }
                            }
                        },
                        {
                            xtype: 'actioncolumn',
                            width: 46,
                            align: 'center',
                            items: [
                                {
                                    handler: function(view, rowIndex, colIndex, item, e, record, row) {
                                        var store=Ext.StoreMgr.get('zbcrsh');
                                        var gf=record.get('crzbbh');

                                        //alert(store.count(true)[gf]);
                                        //alert(store.getGroups().get(gf).children[0]);
                                        //alert(store.group(gf));
                                        if(record.get('crzt')=='待审核')
                                        {
                                            record.set('crzt','通过');
                                            // alert(Number(record.get('crqt'))-1);
                                            //record.set('crqt',Number(record.get('crqt'))-1);
                                            record.commit();

                                            store.each(function(rec){
                                                if(rec.get('crzbbh')==gf)
                                                {
                                                    num=Number(rec.get('crqt'))-1;
                                                    rec.set('crqt',num);
                                                    // alert(rec.get('crqt'));
                                                }
                                            });

                                            // Ext.MessageBox.confirm('提醒','您确定要通过此项记录吗？',function(btn){
                                            // if(btn=='yes')

                                            Ext.Ajax.request(
                                            {
                                                url:'updateshtg',
                                                method:'post',
                                                headers:{

                                                    'Content-Type':'application/json'
                                                },
                                                params:Ext.encode(record.getData()),
                                                success:function(response){
                                                    //var result=Ext.decode(response.responseText);
                                                    Ext.MessageBox.alert('信息','该项记录审核完成');
                                                    //(function() {
                                                    setTimeout(function(){Ext.MessageBox.hide();},1000);
                                                    //}).defer(1000);

                                                },
                                                failure:function(){
                                                    //Ext.MessageBox.alert('错误','操作失败！');
                                                }

                                            }
                                            );
                                        }

                                        //  );

                                        else
                                        {
                                            Ext.MessageBox.alert('信息','该记录已经审核完毕，不能再次审核');
                                        }

                                    },
                                    altText: '通过',
                                    icon: 'images/true.png',
                                    tooltip: '通过'
                                }
                            ],
                            listeners: {
                                afterrender: {
                                    fn: me.onActioncolumnAfterRender,
                                    scope: me
                                }
                            }
                        },
                        {
                            xtype: 'actioncolumn',
                            width: 47,
                            align: 'center',
                            items: [
                                {
                                    handler: function(view, rowIndex, colIndex, item, e, record, row) {
                                        if(record.get('crzt')=='待审核')
                                        {
                                            record.set('crzt','未通过');//alert(Ext.encode(record.getData()));
                                            record.commit();
                                            Ext.MessageBox.confirm('提醒','您确定此记录不通过吗？',function(btn){
                                                if(btn=='yes')
                                                {
                                                    Ext.Ajax.request(
                                                    {
                                                        url:'updateshbtg',
                                                        method:'post',
                                                        headers:{

                                                            'Content-Type':'application/json'
                                                        },
                                                        params:Ext.encode(record.getData()),
                                                        success:function(response){
                                                            //var result=Ext.decode(response.responseText);
                                                            Ext.MessageBox.alert('信息','审核完成',function(btn){
                                                                view.style.backgroundColor = 'red';
                                                            });
                                                        },
                                                        failure:function(){
                                                            //Ext.MessageBox.alert('错误','操作失败！');
                                                        }

                                                    }
                                                    );
                                                }
                                            }
                                            );
                                        }

                                        else
                                        {
                                            Ext.MessageBox.alert('信息','该记录已经审核完毕，不能再次审核');
                                        }

                                    },
                                    altText: '不通过',
                                    icon: 'images/false.png',
                                    tooltip: '不通过'
                                }
                            ],
                            listeners: {
                                afterrender: {
                                    fn: me.onActioncolumnAfterRender1,
                                    scope: me
                                }
                            }
                        },
                        {
                            xtype: 'gridcolumn',
                            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {

                                if(value==null||value=='')

                                return "双击进行编辑";
                                else
                                return value;

                            },
                            dataIndex: 'crbz',
                            text: '备注',
                            tooltip: '备注信息将反馈给申让方',
                            editor: {
                                xtype: 'textfield'
                            }
                        }
                    ],
                    viewConfig: {
                        getRowClass: function(record, rowIndex, rowParams, store) {
                            if(record.get('crzt')=='通过')
                            return 'now';
                            //else
                            //  return 'later';
                        },
                        cls: 'x-grid3-row TD',
                        listeners: {
                            cellclick: {
                                fn: me.onViewCellClick,
                                scope: me
                            }
                        }
                    },
                    plugins: [
                        Ext.create('Ext.grid.plugin.CellEditing', {

                        })
                    ],
                    features: [
                        {
                            ftype: 'grouping',
                            collapsible: false,
                            groupHeaderTpl: [
                                '<font size=\'2px\'>{columnName}: {name}   (本组共{rows.length}个)</font>'
                            ]
                        }
                    ]
                }
            ],
            dockedItems: [
                {
                    xtype: 'pagingtoolbar',
                    dock: 'bottom',
                    width: 360,
                    displayInfo: true,
                    store: 'zbcrsh'
                }
            ]
        });

        me.callParent(arguments);
    },

    onDddddAfterRender: function(component, eOpts) {
        component.setText('指标凭证');
    },

    onViewCellClick: function(tableview, td, cellIndex, record, tr, rowIndex, e, eOpts) {
        /*
        if(cellIndex==11)
        {
            var win=Ext.widget('zbcrshwin');
            win.setTitle(record.get('crzbbh'));
            win.items.get(0).loadRecord(record);
            win.show();
        }
        */

    },

    onActioncolumnAfterRender: function(component, eOpts) {
        component.setText('通过');
    },

    onActioncolumnAfterRender1: function(component, eOpts) {
        component.setText('不通过');
    }

});